/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.button.Button',
        'Ext.toolbar.Paging',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox'
    ],

    viewModel: {
        type: 'myviewport'
    },
    layout: 'fit',

    items: [
        {
            xtype: 'panel',
            height: 650,
            layout: 'border',
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'west',
                    id: 'grid_Seccion',
                    width: 300,
                    title: 'Secciones Intranet',
                    forceFit: true,
                    store: 'jsGetSeccion',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'id',
                            hideable: false,
                            text: 'id'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 245,
                            dataIndex: 'seccion',
                            text: 'Sección'
                        }
                    ],
                    selModel: {
                        selType: 'checkboxmodel'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btn_Refresh_Seccion',
                                    icon: '../../images/refresh.png',
                                    tooltip: 'Refrescar datos'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 2,
                            autoScroll: true,
                            id: 'gridTransaccion',
                            title: 'Transacciones',
                            titleAlign: 'center',
                            forceFit: true,
                            store: 'jsGetTransaccion',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 80,
                                    dataIndex: 'rut',
                                    text: 'Rut'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 250,
                                    dataIndex: 'nombre',
                                    text: 'Nombre'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 250,
                                    dataIndex: 'cargo',
                                    text: 'Cargo'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 250,
                                    dataIndex: 'seccion',
                                    text: 'Sección'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 150,
                                    dataIndex: 'fecha',
                                    text: 'Fecha'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'right',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btn_Exportar_Transaccion',
                                            icon: '../../images/excel.png',
                                            tooltip: 'Exportar datos'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    afterPageText: 'de {0}',
                                    beforePageText: 'Página',
                                    displayInfo: true,
                                    displayMsg: 'Mostrando {0} - {1} of {2}',
                                    emptyMsg: 'Sin datos',
                                    firstText: 'Primera Página',
                                    lastText: 'Última Página',
                                    nextText: 'Siguiente',
                                    prevText: 'Anterior',
                                    refreshText: 'Refrescar',
                                    store: 'jsGetTransaccion'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 3,
                            autoScroll: true,
                            id: 'pnl_Contenedor_Grafico',
                            title: 'Gráfico',
                            titleAlign: 'center'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btn_Grafico_dia',
                                    icon: '../../images/dia.png',
                                    tooltip: 'Tracking por Día'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_Grafico_mes',
                                    icon: '../../images/mes.png',
                                    tooltip: 'Tracking por Mes'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_Grafico_anho',
                                    icon: '../../images/anho.png',
                                    tooltip: 'Tracking por Año'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'form',
                    region: 'north',
                    height: 100,
                    animCollapse: true,
                    bodyPadding: 10,
                    collapsed: false,
                    title: 'Filtros',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            margin: 5,
                            width: 340,
                            title: 'Intervalo de Tiempo',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'datefield',
                                    id: 'fdate_Inicio',
                                    maxWidth: 150,
                                    width: 150,
                                    fieldLabel: 'Inicio',
                                    labelWidth: 50,
                                    format: 'd/m/Y',
                                    submitFormat: 'Ymd'
                                },
                                {
                                    xtype: 'datefield',
                                    id: 'fdate_Termino',
                                    maxWidth: 150,
                                    width: 150,
                                    fieldLabel: 'Término',
                                    labelWidth: 50,
                                    format: 'd/m/Y',
                                    submitFormat: 'Ymd'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            margin: 5,
                            title: 'Colaboradores',
                            items: [
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'cmb_Colaborador',
                                    width: 350,
                                    fieldLabel: 'Colaborador',
                                    labelWidth: 70,
                                    displayField: 'nombre',
                                    store: 'jsGetColaborador',
                                    valueField: 'rut'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            margin: 5,
                            title: 'Aplicar Filtros',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btn_Aplicar_Filtros',
                                    icon: '../../images/buscar.png',
                                    text: 'Filtrar',
                                    tooltip: 'Refrescar datos'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});