/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.column.Check'
    ],

    viewModel: {
        type: 'myviewport'
    },
    layout: 'fit',

    items: [
        {
            xtype: 'form',
            id: 'form_haberes',
            layout: 'fit',
            bodyPadding: 10,
            title: 'Configuración de conceptos de la liquidación',
            items: [
                {
                    xtype: 'gridpanel',
                    header: false,
                    title: 'Configuración de conceptos de la liquidación',
                    store: 'items',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            layout: {
                                type: 'hbox',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {

                                        var form = Ext.getCmp('form_haberes').getForm();
                                        if (form.isValid()) {
                                            form.submit({
                                                url : "../../../servlet/EjeCore?claseweb=cl.eje.view.sencha.ConfSegura&modulo=eje_liquidacion_clasificacionhaberes&thing=Items&accion=upd",
                                                params : { toUpdate: MyApp.app.getController("ctrTool").store_getEncode("items") },
                                                success: function (form, action) {
                                                    Ext.Msg.alert('Success', action.result.msg);
                                                },
                                                failure: function (form, action) {
                                                    Ext.Msg.alert('Failed', action.result.msg);
                                                }
                                            });
                                        }

                                    },
                                    icon: '../../images/btns/tick.ico',
                                    text: 'Guardar'
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'haber',
                            text: 'Haber'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'descrip',
                            text: 'Descrip'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'tipo',
                            text: 'Tipo'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'afec_imp',
                            text: 'Afec Imp'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'imponible',
                            text: 'Imponible'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'id_tp',
                            text: 'Id Tp'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'orden',
                            text: 'Orden'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'wp_cod_empresa',
                            text: 'Wp Cod Empresa'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'wp_cod_planta',
                            text: 'Wp Cod Planta'
                        },
                        {
                            xtype: 'checkcolumn',
                            dataIndex: 'campo1',
                            text: 'Es Variable'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'campo2',
                            text: 'Campo2'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'campo3',
                            text: 'Campo3'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                Ext.getStore("items").load();


                            },
                            icon: '../../images/btns/arrow_refresh.ico',
                            text: ''
                        }
                    ]
                }
            ]
        }
    ]

});