/*
 * File: app/controller/ctrMain.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.ctrMain', {
    extend: 'Ext.app.Controller',

    control: {
        "#btn_Refresh_Seccion": {
            click: 'onButtonClick_Btn_Refresh_Seccion'
        },
        "#btn_Aplicar_Filtros": {
            click: 'onButtonClick_Btn_Aplicar_Filtros'
        },
        "#btn_Exportar_Transaccion": {
            click: 'onButtonClick_Btn_Exportar_Transaccion'
        },
        "#btn_Grafico_dia": {
            click: 'onButtonClick_Btn_Grafico_dia'
        },
        "#btn_Grafico_mes": {
            click: 'onButtonClick_Btn_Grafico_mes'
        },
        "#btn_Grafico_anho": {
            click: 'onButtonClick_Btn_Grafico_anho'
        }
    },

    onButtonClick_Btn_Refresh_Seccion: function(button, e, eOpts) {

    },

    onButtonClick_Btn_Aplicar_Filtros: function(button, e, eOpts) {
        var inicio = Ext.getCmp("fdate_Inicio").getSubmitValue();
        var termino = Ext.getCmp("fdate_Termino").getSubmitValue();
        var colaborador = Ext.getCmp("cmb_Colaborador").getValue();
        if (inicio === "") { inicio = "-1"; }
        if (termino === "") { termino = "-1"; }
        if (colaborador === null) { colaborador = "-1"; }
        Ext.getStore("jsGetTransaccion").load( { params: { "inicio":inicio, "termino":termino, "colaborador": colaborador } } );
        this.fnVerGrafico(1,inicio,termino,colaborador);
    },

    onButtonClick_Btn_Exportar_Transaccion: function(button, e, eOpts) {
        var inicio = Ext.getCmp("fdate_Inicio").getSubmitValue();
        var termino = Ext.getCmp("fdate_Termino").getSubmitValue();
        var colaborador = Ext.getCmp("cmb_Colaborador").getValue();
        if (inicio === "") { inicio = "-1"; }
        if (termino === "") { termino = "-1"; }
        if (colaborador === null) { colaborador = "-1"; }
        window.document.location="../../../servlet/EjeCoreI?claseweb=cl.eje.view.sencha.Conf&modulo=eje_generico_trackingportal&accion=export&thing=Transaccion&inicio="+inicio+"&termino="+termino+"&colaborador="+colaborador;
    },

    onButtonClick_Btn_Grafico_dia: function(button, e, eOpts) {
        var inicio = Ext.getCmp("fdate_Inicio").getSubmitValue();
        var termino = Ext.getCmp("fdate_Termino").getSubmitValue();
        var colaborador = Ext.getCmp("cmb_Colaborador").getValue();
        if (inicio === "") { inicio = "-1"; }
        if (termino === "") { termino = "-1"; }
        if (colaborador === null) { colaborador= "-1"; }
        this.fnVerGrafico(1,inicio,termino,colaborador);
    },

    onButtonClick_Btn_Grafico_mes: function(button, e, eOpts) {
        var inicio = Ext.getCmp("fdate_Inicio").getSubmitValue();
        var termino = Ext.getCmp("fdate_Termino").getSubmitValue();
        var colaborador = Ext.getCmp("cmb_Colaborador").getValue();
        if (inicio === "") { inicio = "-1"; }
        if (termino === "") { termino = "-1"; }
        if (colaborador === null) { colaborador = "-1"; }
        this.fnVerGrafico(2,inicio,termino,colaborador);
    },

    onButtonClick_Btn_Grafico_anho: function(button, e, eOpts) {
        var inicio = Ext.getCmp("fdate_Inicio").getSubmitValue();
        var termino = Ext.getCmp("fdate_Termino").getSubmitValue();
        var colaborador = Ext.getCmp("cmb_Colaborador").getValue();
        if (inicio === "") { inicio = "-1"; }
        if (termino === "") { termino = "-1"; }
        if (colaborador === null) { colaborador = "-1"; }
        this.fnVerGrafico(3,inicio,termino,colaborador);
    },

    fnVerGrafico: function(tipo, inicio, termino, colaborador) {
        $.ajax({
            url: "../../../servlet/EjeCoreI?claseweb=cl.eje.view.sencha.eje_generico_trackingportal.Grafico&tipo="+tipo+"&inicio="+inicio+"&termino="+termino+"&colaborador="+colaborador,
            method: 'POST',
            timeout: 60000000,
            params: { },
            dataType: "text",
            success: function(response){
                var text = response;
                var json = JSON.parse(text);
                if( $("#pnl_Contenedor_Grafico").length > 0) {
                    $("#pnl_Contenedor_Grafico").highcharts(json[0]);
                }
            },
            error: function() {
            }
        });
    }

});
