/*
 * File: app/model/modelPeriodo.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.modelPeriodo', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'peri_id'
        },
        {
            name: 'peri_ano'
        },
        {
            name: 'peri_mes'
        },
        {
            name: 'peri_utm'
        },
        {
            name: 'peri_uf'
        }
    ]
});