/*
 * File: app/model/modelHaberesClasificacion.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.modelHaberesClasificacion', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'id_corr'
        },
        {
            name: 'id_motor'
        },
        {
            name: 'colum_name'
        },
        {
            name: 'alias'
        },
        {
            name: 'id_tp'
        },
        {
            name: 'orden'
        },
        {
            name: 'wp_indic_papeleta'
        },
        {
            name: 'haber_variable'
        },
        {
            name: 'unidad'
        },
        {
            name: 'tip_unidad'
        },
        {
            name: 'definido'
        },
        {
            name: 'is_total'
        },
        {
            name: 'is_liquido'
        }
    ]
});