/*
 * File: app/store/jsonGroupCargo.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.jsonGroupCargo', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.groupCargo_model',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 500,
            storeId: 'jsonGroupCargo',
            model: 'MyApp.model.groupCargo_model',
            proxy: {
                type: 'ajax',
                timeout: 300000,
                url: '../../../EjeCore?claseweb=cl.eje.view.sencha.ConfSegura&modulo=eje_generico_correspondenciaautomatica&thing=Cargos&accion=get',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});