/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.tree.Column',
        'Ext.grid.column.Action',
        'Ext.grid.column.Check',
        'Ext.toolbar.Separator',
        'Ext.selection.CheckboxModel',
        'Ext.grid.Panel',
        'Ext.form.field.Text',
        'Ext.toolbar.Paging',
        'Ext.form.Panel',
        'Ext.form.field.Hidden'
    ],

    viewModel: {
        type: 'myviewport'
    },
    layout: 'fit',
    defaultListenerScope: true,

    listeners: {
        render: 'onViewportRender'
    },
    items: [
        {
            xtype: 'tabpanel',
            width: 150,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    layout: 'fit',
                    header: false,
                    title: 'Administrador de Perfiles',
                    tabConfig: {
                        xtype: 'tab',
                        tooltip: 'Paso 1: Aqu&iacute; es donde podr&aacute;s crear , editar o eliminar perfiles junto con sus respectivas atribuciones.'
                    },
                    items: [
                        {
                            xtype: 'treepanel',
                            height: 150,
                            id: 'grid_Perfiles',
                            scrollable: true,
                            collapsible: true,
                            header: false,
                            title: 'Administrador de Perfiles',
                            forceFit: false,
                            rowLines: true,
                            store: 'js_Tree',
                            rootVisible: false,
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'id',
                                    text: 'id'
                                },
                                {
                                    xtype: 'treecolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if (record.data.is_default === "true" || record.data.is_default === true) {
                                            metaData.style = 'background-image: url(../../images/btns/star.ico);background-repeat: no-repeat; background-position: 3px center; padding-left: 16px;';
                                        }else{
                                            metaData.style = 'background-image: none;background-repeat: no-repeat; background-position: 3px center; padding-left: 16px;';
                                        }
                                        return value;
                                    },
                                    minWidth: 350,
                                    width: 350,
                                    dataIndex: 'text',
                                    text: 'Perfil'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    maxWidth: 60,
                                    minWidth: 60,
                                    width: 60,
                                    align: 'center',
                                    dataIndex: 'cant_usuarios',
                                    menuDisabled: true,
                                    text: 'Cantidad<br>Usuarios'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    menuDisabled: true,
                                    text: 'Accesos',
                                    columns: [
                                        {
                                            xtype: 'actioncolumn',
                                            height: 0,
                                            maxWidth: 25,
                                            minWidth: 25,
                                            width: 25,
                                            menuDisabled: true,
                                            icon: '',
                                            items: [
                                                {
                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                        MyApp.app.getController("ctrTool").fnShowWindow("window_personasperfil", null, {id_perfil: record.get("id")});
                                                    },
                                                    icon: '../../images/btns/folder_user.png',
                                                    tooltip: 'Usuarios asignados'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            height: 0,
                                            maxWidth: 25,
                                            minWidth: 25,
                                            width: 25,
                                            menuDisabled: true,
                                            items: [
                                                {
                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                        var params = {
                                                            func: function(json) {
                                                                console.log(Ext.encode(json));
                                                                record.set('user_app', Ext.encode(json));
                                                            },
                                                            strJson: record.get('user_app')
                                                        };

                                                        ctr.Tool.fnShowWindow('window_zonasadministracion', null, params);

                                                    },
                                                    icon: '../../images/btns/account_menu.ico',
                                                    tooltip: 'Atribuciones de administración'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            height: 0,
                                            maxWidth: 25,
                                            minWidth: 25,
                                            width: 25,
                                            dataIndex: 'cant_usuarios',
                                            menuDisabled: true,
                                            tooltip: 'Acceso a zonas del autoservicio',
                                            items: [
                                                {
                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                        MyApp.app.getController("ctrTool")
                                                        .fnShowWindow("window_preview", null,
                                                        {func: function(json) {
                                                            console.log(Ext.encode(json));

                                                            record.set("botones_webmatico", Ext.encode(json));
                                                        },
                                                    strJson: record.get("botones_webmatico") });
                                                    },
                                                    icon: '../../images/btns/application_view_icons.ico',
                                                    tooltip: 'Zonas del Portal de Autoconsultas'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'actioncolumn',
                                            height: 0,
                                            hidden: true,
                                            width: 25,
                                            menuDisabled: true,
                                            icon: '../../images/btns/edit_recipient_list.ico',
                                            items: [
                                                {
                                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                        MyApp.app.getController("ctrTool")
                                                        .fnShowWindow("window_preview", null,
                                                        {func: function(json) {
                                                            console.log(Ext.encode(json));

                                                            record.set("eje_ges_user_app", Ext.encode(json));
                                                        },
                                                    strJson: record.get("eje_ges_user_app") });

                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridcolumn',
                                    text: 'Zona "Mi equipo"',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            menuDisabled: true,
                                            text: 'Ficha Digital',
                                            columns: [
                                                {
                                                    xtype: 'checkcolumn',
                                                    height: 50,
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'op1',
                                                    text: 'Datos <br/> Personales'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'op2',
                                                    text: 'Remune<br/>raciones'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'op3',
                                                    text: 'Datos <br/> Previsio<br/>nales'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'op4',
                                                    text: 'Datos <br/> Contrac<br/>tuales'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'op5',
                                                    text: 'Vaca<br/>ciones'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'op6',
                                                    text: 'Licencias <br/>Médicas'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'op7',
                                                    text: 'Comisiones'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'op8',
                                                    text: 'Grupo<br/>Familiar'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'op9',
                                                    text: 'Estudios'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'op10',
                                                    text: 'Trayectoria<br/>Laboral'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            menuDisabled: true,
                                            text: 'Reportes Orgánica',
                                            columns: [
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'costos',
                                                    text: 'Costos'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'dotacion',
                                                    text: 'Dotación'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'cargos',
                                                    text: 'Cargos'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'tipo_contrato',
                                                    text: 'Tipo<br/> Contrato'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'costos_empresa',
                                                    text: 'Costos<br/>Empresa'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'ingresos',
                                                    text: 'Ingresos'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'egresos',
                                                    text: 'Egresos'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'resumen_in_out',
                                                    text: 'Resumen<br/>in/out'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'saldo_vacaciones',
                                                    text: 'Saldo<br/>Vacaciones'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'grupo_familiar',
                                                    text: 'Grupo<br/>Familiar'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'estudios',
                                                    text: 'Estudios'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridcolumn',
                                    text: 'Zona "Estructura"',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            menuDisabled: true,
                                            text: 'Ficha Digital',
                                            columns: [
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'miestruc_op1',
                                                    text: 'Datos<br/>Personales'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'miestruc_op2',
                                                    text: 'Remuneraciones'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'miestruc_op3',
                                                    text: 'Datos<br/>Previsionales'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'miestruc_op4',
                                                    text: 'Datos<br/>Contractuales'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'miestruc_op5',
                                                    text: 'Vacaciones'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'miestruc_op6',
                                                    text: 'Licencias<br/>M\u00e9dicas'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'miestruc_op7',
                                                    text: 'Comisiones'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'miestruc_op8',
                                                    text: 'Grupo<br/>Familiar'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'miestruc_op9',
                                                    text: 'Estudios'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    maxWidth: 70,
                                                    minWidth: 70,
                                                    width: 70,
                                                    dataIndex: 'miestruc_op10',
                                                    text: 'Trayectoria<br/>Laboral'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            menuDisabled: true,
                                            text: 'Reportes Orgánica',
                                            columns: [
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'miestruc_costos',
                                                    text: 'Costos'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'miestruc_dotacion',
                                                    text: 'Dotaci\u00f3n'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'miestruc_cargos',
                                                    text: 'Cargos'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'miestruc_tipo_contrato',
                                                    text: 'Tipo<br/>Contrato'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'miestruc_costos_empresa',
                                                    text: 'Costos<br/>Empresa'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'miestruc_ingresos',
                                                    text: 'Ingresos'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'miestruc_egresos',
                                                    text: 'Egresos'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'miestruc_resumen_in_out',
                                                    text: 'Resumen<br/>in/out'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'miestruc_saldo_vacaciones',
                                                    text: 'Saldo<br/>Vacaciones'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'miestruc_estudios',
                                                    text: 'Estudios'
                                                },
                                                {
                                                    xtype: 'checkcolumn',
                                                    width: 70,
                                                    dataIndex: 'miestruc_grupo_familiar',
                                                    text: 'Grupo<br/>Familiar'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {

                                                var panel = Ext.getCmp('grid_Perfiles');
                                                var record = panel.getSelectionModel().getSelection()[0];


                                                if( record != null ) {
                                                    var store = panel.getStore();
                                                    var i = 0;

                                                    store.data.each(function(lRecord) {
                                                        lRecord.set("is_default", null);
                                                    });

                                                    record.set("is_default","true");
                                                }


                                            },
                                            id: 'btn_porDefecto',
                                            icon: '../../images/btns/star.ico',
                                            text: '',
                                            tooltip: 'Fijar perfil por defecto'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btn_Perfiles_Add',
                                            icon: '../../images/btns/add.png',
                                            tooltip: 'Agregar Perfil',
                                            listeners: {
                                                click: 'onBtn_Perfiles_AddClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btn_Perfiles_Delete',
                                            icon: '../../images/btns/delete.png',
                                            tooltip: 'Eliminar Perfiles',
                                            listeners: {
                                                click: 'onBtn_Perfiles_DeleteClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btn_Perfiles_Save',
                                            icon: '../../images/btns/save_data.ico',
                                            tooltip: 'Grabar Cambios',
                                            listeners: {
                                                click: 'onBtn_Perfiles_SaveClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btn_Perfiles_Refresh',
                                            icon: '../../images/btns/refresh.png',
                                            tooltip: 'Refrescar Perfiles',
                                            listeners: {
                                                click: 'onBtn_Perfiles_RefreshClick'
                                            }
                                        }
                                    ]
                                }
                            ],
                            selModel: {
                                selType: 'checkboxmodel',
                                mode: 'SINGLE',
                                checkOnly: true,
                                listeners: {
                                    select: 'onCheckboxModelSelect'
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    selectPersona: function() {
                        var selected = Ext.getCmp("grid_usuarios").getSelectionModel().getSelection();
                        //console.log(selected);

                        var ruts = (MyApp.app.getController("ctrTool").grid_getSelectedEncode("grid_usuarios","rut"));
                        //console.log(ruts);

                        if(selected.length > 0) {
                            var p = Ext.getStore("js_Perfiles").getProxy();
                            p.setExtraParam("ruts", ruts );
                            Ext.getStore("js_Perfiles").load();
                            //Ext.getStore("js_Perfiles").load({params : { "ruts" : ruts } });
                            Ext.getCmp("grid_Perfil").setDisabled(false);
                        }
                        else {
                            Ext.getCmp("grid_Perfil").setDisabled(true);
                        }

                    },
                    id: 'perfiles_persona',
                    layout: 'fit',
                    title: 'Perfiles',
                    tabConfig: {
                        xtype: 'tab',
                        tooltip: 'Paso 2: Aqu&iacute; podr&aacute;s establecer el perfil que posee cada una de las personas de la compa&ntilde;ia.'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    height: 250,
                                    id: 'grid_usuarios',
                                    width: 400,
                                    title: 'Usuarios',
                                    forceFit: true,
                                    store: 'js_Colaborador',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'nombre',
                                            text: 'Nombre'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                return "<img src='../../images/btns/perfil.png' title='Perfiles " + record.get("nombre") + "' >";
                                            },
                                            maxWidth: 30,
                                            minWidth: 30,
                                            width: 30,
                                            dataIndex: 'rut'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            search: function() {
                                                var filtro = Ext.getCmp("txt_Colaborador_Filtro").getValue();
                                                Ext.getStore("js_Colaborador").getProxy().setExtraParam("filtro", filtro);
                                                Ext.getStore("js_Colaborador").getProxy().setExtraParam("filtroPersonas", Ext.getCmp("hidden_cargos").getValue());

                                                Ext.getStore("js_Colaborador").load();


                                            },
                                            dock: 'top',
                                            id: 'toolbar_search',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    id: 'txt_Colaborador_Filtro',
                                                    enableKeyEvents: true,
                                                    listeners: {
                                                        specialkey: 'onTxt_Colaborador_FiltroSpecialkey'
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, e) {
                                                        Ext.getCmp("toolbar_search").search();

                                                    },
                                                    icon: '../../images/btns/search_accounts.ico',
                                                    text: ''
                                                },
                                                {
                                                    xtype: 'tbseparator',
                                                    hidden: true
                                                },
                                                {
                                                    xtype: 'button',
                                                    hidden: true,
                                                    id: 'bnt_Colaborador_Search',
                                                    icon: '../../images/btns/filter.png',
                                                    tooltip: 'Buscar Colaboradores',
                                                    listeners: {
                                                        click: 'onBnt_Colaborador_SearchClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    handler: function(button, e) {
                                                        MyApp.app.getController("ctrTool").fnShowWindow("window_cargo");
                                                    },
                                                    hidden: true,
                                                    icon: '../../images/btns/filter_add.png',
                                                    text: ''
                                                },
                                                {
                                                    xtype: 'button',
                                                    hidden: true,
                                                    id: 'btn_Colaborador_Refresh',
                                                    icon: '../../images/btns/refresh.png',
                                                    tooltip: 'Refrescar Colaboradores',
                                                    listeners: {
                                                        click: 'onBtn_Colaborador_RefreshClick'
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            width: 360,
                                            displayInfo: true,
                                            store: 'js_Colaborador'
                                        }
                                    ],
                                    selModel: {
                                        selType: 'checkboxmodel'
                                    },
                                    listeners: {
                                        selectionchange: 'onGrid_usuariosSelectionChange'
                                    }
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    disabled: true,
                                    id: 'grid_Perfil',
                                    scrollable: true,
                                    title: 'Asignar Perfiles',
                                    forceFit: true,
                                    store: 'js_Perfiles',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'id',
                                            text: 'id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'rut',
                                            text: 'rut'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'nombre',
                                            text: 'Perfil'
                                        },
                                        {
                                            xtype: 'checkcolumn',
                                            maxWidth: 25,
                                            minWidth: 25,
                                            width: 25,
                                            dataIndex: 'tiene',
                                            groupable: false,
                                            menuDisabled: true,
                                            listeners: {
                                                checkchange: 'onCheckcolumnCheckChange'
                                            }
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    id: 'btn_Perfil_Save',
                                                    icon: '../../images/btns/save_data.ico',
                                                    tooltip: 'Asociar Perfiles',
                                                    listeners: {
                                                        click: 'onBtn_Perfil_SaveClick'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    hidden: true,
                                    id: 'frm_Perfiles',
                                    bodyPadding: 10,
                                    title: 'My Form',
                                    items: [
                                        {
                                            xtype: 'hiddenfield',
                                            anchor: '100%',
                                            id: 'hidden_cargos',
                                            fieldLabel: 'Label'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onViewportRender: function(component, eOpts) {
                Ext.getStore("js_cargos").load();
                //Ext.getStore("js_Tree").load();

    },

    onBtn_Perfiles_AddClick: function(button, e, eOpts) {
        console.log("onBtn_Perfiles_AddClick");

        Ext.MessageBox.prompt('Perfil', 'Ingrese Nombre del Nuevo Perfil:', showResultText);


        function showResultText(btn, text){

            if(btn == "ok") {

                //inicio
                var perfil = text;
                var form = Ext.getCmp("frm_Perfiles").getForm();
                var error=false;

                form.submit({
                    url:"../../../servlet/EjeCoreI?claseweb=cl.eje.view.sencha.Conf&modulo=eje_generico_gestionperfiles&accion=add&thing=TreePerfiles",
                    method: "POST",
                    params:	{ "perfil" : perfil },
                    waitMsg	: 'Agregando Nuevo Perfil, espere por favor...',
                    success	: function(form,result){
                        try {
                            var data = Ext.JSON.decode(result.response.responseText);
                            console.log(data);

                            if (data.success==="true" || data.success===true){
                                Ext.Msg.show({
                                    title: 'Nuevo Perfil',
                                    msg: 'El Perfil se creo correctamente.',
                                    buttons: Ext.Msg.OK,
                                    icon: Ext.Msg.INFO
                                });
                                Ext.getStore("js_Tree").load();
                                Ext.getStore("js_Colaborador").load();
                                Ext.getStore("js_Perfiles").removeAll();
                            }
                            else{
                                error=true;
                            }
                        }
                        catch(e){
                            error=true;
                        }
                        if (error===true){
                            var mensg='<p>Ha ocurido un error con algunos de los datos al tratar de grabar la informaci\u00f3n.</p> ';
                            mensg=mensg+'<p>Verifique los datos y por favor int\u00e9ntelo nuevamente.</p> ';
                            Ext.Msg.show({
                                title: 'Error inesperado',
                                msg: mensg,
                                buttons: Ext.Msg.OK,
                                icon: Ext.Msg.ERROR
                            });
                        }
                    },
                    complete: function() {

                    }
                });
            //fin aisgnacion perfiles
            }
        }
    },

    onBtn_Perfiles_DeleteClick: function(button, e, eOpts) {
        console.log("onBtn_Perfiles_DeleteClick");

        var x = 0;
        var panel = Ext.getCmp('grid_Perfiles');
        var seleccionados=panel.getSelectionModel().getSelection();

        console.log(seleccionados);

        if (seleccionados.length>0){

            Ext.MessageBox.confirm('Perfil', '¿Está seguro de querer eliminar el perfil seleccionado?', function showResultText(btn, text){
                console.log(btn);

                if(btn == "ok" || btn == "yes") {
                    Ext.each(seleccionados, function(record, index, allRecords) {
                        var perfil = record.get('id');
                        Ext.getStore('js_Deleteperfil').load({params:{"perfil":perfil}});


                    });
                    Ext.getStore("js_Colaborador").load();
                    Ext.getStore("js_Perfiles").removeAll();
                    Ext.getStore("js_Tree").load();
                }

            });
        }
        else {
            Ext.Msg.alert("Perfil", "Primero debe seleccionar un perfil");
        }
    },

    onBtn_Perfiles_SaveClick: function(button, e, eOpts) {
        console.log("onBtn_Perfiles_SaveClick");

        //inicio
        var form = Ext.getCmp("frm_Perfiles").getForm();
        var error=false;
        var perfil = 0;
        var arrData = [];
        Ext.getCmp("grid_Perfiles").store.each(function(record) {
            var n = record.data.id;
            if ( n ) {
                var id_perfil = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.id;
                var nombre 	  = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.text;
                var is_default = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.is_default;

                /* ZONA MI EQUIPO */
                var op1 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.op1;
                var op2 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.op2;
                var op3 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.op3;
                var op4 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.op4;
                var op5 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.op5;
                var op6 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.op6;
                var op7 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.op7;
                var op8 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.op8;
                var op9 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.op9;
                var op10 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.op10;

                var miestruc_op1 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_op1;
                var miestruc_op2 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_op2;
                var miestruc_op3 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_op3;
                var miestruc_op4 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_op4;
                var miestruc_op5 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_op5;
                var miestruc_op6 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_op6;
                var miestruc_op7 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_op7;
                var miestruc_op8 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_op8;
                var miestruc_op9 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_op9;
                var miestruc_op10 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_op10;
                /* END ZONA MI EQUIPO */

                /* ZONA ESTRUCTURA*/
                var costos 	 		= Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.costos;
                var dotacion 		= Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.dotacion;
                var cargos	 		= Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.cargos;
                var tipo_contrato 	= Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.tipo_contrato;
                var costos_empresa 	= Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.costos_empresa;
                var ingresos		= Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.ingresos;
                var egresos			= Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.egresos;
                var resumen_in_out	= Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.resumen_in_out;
                var saldo_vacaciones= Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.saldo_vacaciones;
                var estudios		= Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.estudios;
                var grupo_familiar	= Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.grupo_familiar;

                var miestruc_costos 	 	 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_costos;
                var miestruc_dotacion 		 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_dotacion;
                var miestruc_cargos	 		 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_cargos;
                var miestruc_tipo_contrato 	 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_tipo_contrato;
                var miestruc_costos_empresa	 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_costos_empresa;
                var miestruc_ingresos		 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_ingresos;
                var miestruc_egresos		 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_egresos;
                var miestruc_resumen_in_out	 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_resumen_in_out;
                var miestruc_saldo_vacaciones= Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_saldo_vacaciones;
                var miestruc_estudios		 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_estudios;
                var miestruc_grupo_familiar	 = Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.miestruc_grupo_familiar;
                /* END ZONA ESTRUCTURA */

                var botones_webmatico=Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.botones_webmatico;
                var user_app=Ext.getCmp("grid_Perfiles").getStore().getAt(perfil).data.user_app;

                var jsonArray = {"perfil":id_perfil,"nombre":nombre, "is_default": is_default ,
                                 "op1":op1,"op2":op2,"op3":op3,"op4":op4,"op5":op5,"op6":op6,"op7":op7,"op8":op8,"op9":op9,"op10":op10,
                                 "miestruc_op1":miestruc_op1,
                                 "miestruc_op2":miestruc_op2,
                                 "miestruc_op3":miestruc_op3,
                                 "miestruc_op4":miestruc_op4,
                                 "miestruc_op5":miestruc_op5,
                                 "miestruc_op6":miestruc_op6,
                                 "miestruc_op7":miestruc_op7,
                                 "miestruc_op8":miestruc_op8,
                                 "miestruc_op9":miestruc_op9,
                                 "miestruc_op10":miestruc_op10,
                                 costos: costos, dotacion: dotacion, cargos: cargos, tipo_contrato : tipo_contrato,costos_empresa: costos_empresa, ingresos : ingresos,egresos: egresos, resumen_in_out: resumen_in_out , saldo_vacaciones: saldo_vacaciones, estudios: estudios, grupo_familiar: grupo_familiar,
                                 miestruc_costos:miestruc_costos,
                                 miestruc_dotacion:miestruc_dotacion,
                                 miestruc_cargos:miestruc_cargos,
                                 miestruc_tipo_contrato:miestruc_tipo_contrato,
                                 miestruc_costos_empresa:miestruc_costos_empresa,
                                 miestruc_ingresos:miestruc_ingresos,
                                 miestruc_egresos: miestruc_egresos,
                                 miestruc_resumen_in_out:miestruc_resumen_in_out,
                                 miestruc_saldo_vacaciones:miestruc_saldo_vacaciones,
                                 miestruc_estudios:miestruc_estudios,
                                 miestruc_grupo_familiar:miestruc_grupo_familiar,
                                 botones_webmatico: botones_webmatico,
                                 user_app: user_app};

                arrData.push(jsonArray);

                console.log(jsonArray);
            }
            perfil+=1;
        });
        form.submit({
            url:"../../../servlet/EjeCoreI?claseweb=cl.eje.view.sencha.Conf&modulo=eje_generico_gestionperfiles&accion=save&thing=TreePerfiles",
            method: "POST",
            params:	{ "perfiles" : Ext.encode(arrData) },
            waitMsg	: 'Actualizando Perfiles, espere por favor...',
            success	: function(form,result){
                try {
                    var data = Ext.JSON.decode(result.response.responseText);
                    console.log(data);

                    if (data.success == "true" || data.success==true){
                        Ext.Msg.show({
                            title: 'Actualizacion Perfiles',
                            msg: 'Los Perfiles fueron actualizados correctamente.',
                            buttons: Ext.Msg.OK,
                            icon: Ext.Msg.INFO
                        });
                        Ext.getStore("js_Tree").load();
                        Ext.getStore("js_Colaborador").load();
                        Ext.getStore("js_Perfiles").removeAll();
                    }
                    else{
                        var mensg='<p>Ha ocurido un error con algunos de los datos al tratar de grabar la informaci\u00f3n.</p> ';
                        mensg=mensg+'<p>Verifique los datos y por favor int\u00e9ntelo nuevamente.</p> ';
                        Ext.Msg.show({
                            title: 'Error inesperado',
                            msg: mensg,
                            buttons: Ext.Msg.OK,
                            icon: Ext.Msg.ERROR
                        });
                    }
                }
                catch(e){
                    error=true;
                }

            },
            complete: function() {

            }
        });
        //fin aisgnacion perfiles
    },

    onBtn_Perfiles_RefreshClick: function(button, e, eOpts) {
            console.log("onBtn_Perfiles_RefreshClick");

            Ext.MessageBox.confirm('Perfil',
                                   'Al refrescar se perderán todos los cambios que no han sido guardados <br/> ¿Desea continuar? ',
                                   function(btn) {
                                        console.log(btn);
                                        if(btn == "ok" || btn == "yes") {
                                            Ext.getStore("js_Tree").load();
                                        }
                                   });


    },

    onCheckboxModelSelect: function(rowmodel, record, index, eOpts) {
                    console.log(record.get("is_default"));
    },

    onTxt_Colaborador_FiltroSpecialkey: function(field, e, eOpts) {
        if(e.getKey() == 13) {
            Ext.getCmp("toolbar_search").search();
        }

    },

    onBnt_Colaborador_SearchClick: function(button, e, eOpts) {
        var filtro = Ext.getCmp("txt_Colaborador_Filtro").getValue();
        Ext.getStore("js_Colaborador").getProxy().setExtraParam("filtro", filtro);
        Ext.getStore("js_Colaborador").getProxy().setExtraParam("filtroPersonas", Ext.getCmp("hidden_cargos").getValue());

        Ext.getStore("js_Colaborador").load();

    },

    onBtn_Colaborador_RefreshClick: function(button, e, eOpts) {
        Ext.getStore("js_Colaborador").load();
        Ext.getStore("js_Perfiles").removeAll();
    },

    onGrid_usuariosSelectionChange: function(model, selected, eOpts) {



        Ext.getCmp("perfiles_persona").selectPersona();
    },

    onCheckcolumnCheckChange: function(checkcolumn, rowIndex, checked, eOpts) {
        var checkRecord = checkcolumn.up('grid').store.getAt(rowIndex);

        Ext.getCmp("grid_Perfil").getStore().each(function(record){
            if(checkRecord.get("id") != record.get("id")) {
                record.set(checkcolumn.dataIndex,false);
            }
        });



    },

    onBtn_Perfil_SaveClick: function(button, e, eOpts) {
        //inicio asignacion perfiles Colaborador
        var form = Ext.getCmp("frm_Perfiles").getForm();
        var error=false;
        var perfil = 0;
        var arrData = [];
        var elRut = 0;
        var i = 0;
        Ext.getCmp("grid_Perfil").store.each(function(record) {
            if(i===0) {
                elRut = record.data.rut;
                i=1;
            }
            var n = record.data.tiene;
            if ( n ) {
                var id_perfil = Ext.getCmp("grid_Perfil").getStore().getAt(perfil).data.id;
                var rut = Ext.getCmp("grid_Perfil").getStore().getAt(perfil).data.rut;
                arrData.push({"perfil":id_perfil,"rut":rut});
            }
            perfil+=1;
        });

        var ruts = (MyApp.app.getController("ctrTool").grid_getSelectedEncode("grid_usuarios","rut"));
        var perfiles = (MyApp.app.getController("ctrTool").store_getEncode("js_Perfiles"));

        form.submit({
            url:"../../../servlet/EjeCoreI?claseweb=cl.eje.view.sencha.Conf&modulo=eje_generico_gestionperfiles&accion=save&thing=Perfil",
            method: "POST",
            params:	{ "perfiles" : perfiles ,"rut": elRut , "ruts" : ruts },
            waitMsg	: 'Asignando Perfiles al Colaborador, espere por favor...',
            success	: function(form,result){
                try {
                    var data = Ext.JSON.decode(result.response.responseText);
                    if (data.success==="true" || data.success===true){
                        Ext.Msg.show({
                            title: 'Asignacion Perfiles',
                            msg: 'Los Perfiles fueron asignados al Colaborador correctamente.',
                            buttons: Ext.Msg.OK,
                            icon: Ext.Msg.INFO
                        });
                        Ext.getStore("js_Perfiles").load({params: {'rut': elRut}});
                    }
                    else{
                        error=true;
                    }
                }
                catch(e){
                    error=true;
                }
                if (error===true){
                    var mensg='<p>Ha ocurido un error con algunos de los datos al tratar de grabar la informaci\u00f3n.</p> ';
                    mensg=mensg+'<p>Verifique los datos y por favor int\u00e9ntelo nuevamente.</p> ';
                    Ext.Msg.show({
                        title: 'Error inesperado',
                        msg: mensg,
                        buttons: Ext.Msg.OK,
                        icon: Ext.Msg.ERROR
                    });
                }
            },
            complete: function() {

            }
        });
        //fin aisgnacion perfiles
    }

});