/*
 * File: app/view/window_cargo.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.window_cargo', {
    extend: 'Ext.window.Window',
    alias: 'widget.window_cargo',

    requires: [
        'MyApp.view.window_cargoViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Number',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'window_cargo'
    },
    constrain: true,
    height: 494,
    id: 'window_cargo',
    width: 400,
    layout: 'fit',
    title: 'Cargos',
    maximizable: true,
    minimizable: true,
    modal: true,

    items: [
        {
            xtype: 'gridpanel',
            height: 250,
            id: 'grid_cargo',
            width: 400,
            header: false,
            title: 'My Grid Panel',
            store: 'js_cargos',
            selModel: {
                selType: 'checkboxmodel'
            },
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'js_cargos'
                }
            ],
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'cargo',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'descrip',
                    text: 'Cargo',
                    flex: 1
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            layout: {
                type: 'hbox',
                pack: 'end'
            },
            items: [
                {
                    xtype: 'button',
                    hidden: true,
                    icon: '../../images/btns/cross.ico',
                    text: 'Cancelar'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {

                        Ext.getCmp("hidden_cargos").setValue(MyApp.app.getController("ctrTool").grid_getSelected("grid_cargo", "cargo"));
                        Ext.getCmp("window_cargo").destroy();

                    },
                    icon: '../../images/btns/tick.ico',
                    text: 'Aceptar'
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.getStore("js_cargos").load();
                    },
                    icon: '../../images/btns/arrow_refresh.ico',
                    text: ''
                }
            ]
        }
    ]

});