/*
 * File: app/model/ISM/mdlMapa.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.ISM.mdlMapa', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.Number',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            name: 'tipo'
        },
        {
            type: 'int',
            name: 'idusuario'
        },
        {
            name: 'usuario'
        },
        {
            name: 'cargo'
        },
        {
            name: 'foto'
        },
        {
            type: 'float',
            name: 'latmrk'
        },
        {
            type: 'float',
            name: 'lonmrk'
        },
        {
            type: 'float',
            name: 'distancia'
        },
        {
            type: 'date',
            name: 'fecha',
            dateReadFormat: 'Y-m-d H:i:s'
        },
        {
            name: 'hora'
        }
    ]
});