/*
 * File: app/model/ISM/mdlTreeLocal.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.ISM.mdlTreeLocal', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            type: 'int',
            name: 'idcadena'
        },
        {
            type: 'int',
            name: 'idlocal'
        },
        {
            name: 'text'
        },
        {
            name: 'icon'
        },
        {
            type: 'boolean',
            name: 'expanded'
        },
        {
            type: 'boolean',
            name: 'leaf'
        },
        {
            type: 'boolean',
            name: 'activo'
        }
    ]
});