/*
 * File: app/view/ISM/PorPersona/mwPersonas.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ISM.PorPersona.mwPersonas', {
    extend: 'Ext.window.Window',
    alias: 'widget.ismporpersonamwpersonas',

    requires: [
        'MyApp.view.ISM.PorPersona.mwPersonasViewModel',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.grid.column.Column',
        'Ext.selection.CheckboxModel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'ismporpersonamwpersonas'
    },
    constrain: true,
    height: 461,
    id: 'ISMPorPersonamwPersonas',
    width: 395,
    layout: 'fit',
    title: 'Personas',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            id: 'gpnISM_Personas',
            store: 'ISM.PorPersona.jsGetPersonas',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            id: 'tbxISM_Persona_Filtro',
                            width: 322,
                            fieldLabel: 'Filtro',
                            labelWidth: 30
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'nombre',
                    text: 'Nombre',
                    flex: 1
                }
            ],
            selModel: {
                selType: 'checkboxmodel'
            }
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            width: 26,
            layout: {
                type: 'hbox',
                pack: 'end'
            },
            items: [
                {
                    xtype: 'button',
                    id: 'btnISM_Personas_Aceptar',
                    icon: '../../../Tool?images/btns/ok.png',
                    text: 'Aceptar'
                },
                {
                    xtype: 'button',
                    id: 'btnISM_Personas_Cancelar',
                    icon: '../../../Tool?images/btns/cross.png',
                    text: 'Cancelar',
                    listeners: {
                        click: 'onBtnISM_Personas_CancelarClick'
                    }
                }
            ]
        }
    ],

    onBtnISM_Personas_CancelarClick: function(button, e, eOpts) {
        this.close();
    }

});