/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'Ext.Img',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.slider.Single',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Paging',
        'Ext.form.field.Number',
        'Ext.grid.feature.Grouping',
        'Ext.grid.plugin.RowEditing',
        'Ext.grid.column.Action',
        'Ext.form.Panel'
    ],

    viewModel: {
        type: 'myviewport'
    },
    id: 'MyViewport',
    layout: 'fit',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            layout: 'border',
            title: 'Informe Seguimiento Marcadores',
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    region: 'center',
                    split: false,
                    layout: 'border',
                    items: [
                        {
                            xtype: 'panel',
                            region: 'west',
                            split: true,
                            maxWidth: 306,
                            width: 306,
                            collapsible: true,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    flex: 1,
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'image',
                                            height: 22,
                                            width: 60,
                                            src: '../../images/fondo/anywhere_solutions.png'
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnISM_Generar',
                                            icon: '../../images/btns/table_refresh.png',
                                            text: 'Generar'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'btnISM_Descargar',
                                            icon: '../../images/btns/page_excel.png',
                                            text: 'Descargar'
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'combobox',
                                    hidden: true,
                                    id: 'cmbISM_Cliente',
                                    margin: 5,
                                    width: 245,
                                    fieldLabel: 'Cliente',
                                    labelWidth: 40,
                                    displayField: 'nombre',
                                    store: 'ISM.jsGetClientes',
                                    valueField: 'idcliente'
                                },
                                {
                                    xtype: 'container',
                                    margin: '3 0 0 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            id: 'dteISM_Desde',
                                            margin: '0 5 5 5',
                                            width: 140,
                                            fieldLabel: 'Desde',
                                            labelWidth: 40
                                        },
                                        {
                                            xtype: 'datefield',
                                            id: 'dteISM_Hasta',
                                            margin: '0 5 5 0',
                                            width: 140,
                                            fieldLabel: 'Hasta',
                                            labelWidth: 40
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    layout: 'fit',
                                    items: [
                                        {
                                            xtype: 'slider',
                                            hidden: true,
                                            id: 'sldISM_Radio',
                                            margin: '0 5 5 5',
                                            fieldLabel: 'Radio (10mts.)',
                                            value: 10,
                                            increment: 1,
                                            maxValue: 2000,
                                            minValue: 10
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tabpanel',
                                    flex: 1,
                                    id: 'tpnISM_Panel',
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            title: 'Por Persona',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    flex: 1,
                                                    id: 'gpnISM_PorPersona_Personas',
                                                    margin: 2,
                                                    store: 'ISM.PorPersona.dsPersonas',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'nombre',
                                                            text: 'Personas',
                                                            flex: 1
                                                        }
                                                    ],
                                                    dockedItems: [
                                                        {
                                                            xtype: 'toolbar',
                                                            dock: 'right',
                                                            width: 26,
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'btnISM_PorLocal_Persona_Add',
                                                                    icon: '../../images/btns/table_row_insert.png'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'btnISM_PorLocal_Persona_Del',
                                                                    icon: '../../images/btns/table_row_delete.png'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'treepanel',
                                                    flex: 1,
                                                    hidden: true,
                                                    id: 'tpnISM_PorPersona_Local',
                                                    margin: 2,
                                                    title: 'Cadenas - Locales',
                                                    hideHeaders: true,
                                                    store: 'ISM.PorPersona.tsLocales',
                                                    displayField: 'text',
                                                    rootVisible: false,
                                                    viewConfig: {

                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            hidden: true,
                                            title: 'Por Local',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'treepanel',
                                                    flex: 1,
                                                    id: 'tpnISM_PorLocal_Local',
                                                    margin: 2,
                                                    title: 'Cadenas - Locales',
                                                    hideHeaders: true,
                                                    store: 'ISM.PorLocal.tsLocales',
                                                    displayField: 'text',
                                                    rootVisible: false,
                                                    viewConfig: {

                                                    }
                                                },
                                                {
                                                    xtype: 'gridpanel',
                                                    flex: 1,
                                                    id: 'gpnISM_PorLocal_Personas',
                                                    margin: 2,
                                                    store: 'ISM.PorLocal.jsGetPersonas',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'nombre',
                                                            text: 'Personas',
                                                            flex: 1
                                                        }
                                                    ],
                                                    selModel: {
                                                        selType: 'checkboxmodel'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            region: 'center',
                            layout: 'border',
                            header: false,
                            title: 'My Panel',
                            items: [
                                {
                                    xtype: 'container',
                                    region: 'center',
                                    layout: 'border',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            region: 'center',
                                            id: 'pnlISM_Descanso',
                                            layout: 'fit',
                                            header: false,
                                            title: 'My Tab'
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            region: 'south',
                                            split: true,
                                            height: 150,
                                            id: 'grillaDetalle',
                                            collapsible: true,
                                            title: 'Detalle',
                                            store: 'jsGetDetallenEW',
                                            dockedItems: [
                                                {
                                                    xtype: 'pagingtoolbar',
                                                    dock: 'bottom',
                                                    width: 360,
                                                    displayInfo: true,
                                                    store: 'jsGetDetallenEW'
                                                }
                                            ],
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    hidden: true,
                                                    dataIndex: 'nombreusuario',
                                                    text: 'Nombreusuario'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    hidden: true,
                                                    dataIndex: 'titulo',
                                                    text: 'Titulo'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'nombreusuario',
                                                    text: 'Nombreusuario',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'idcorr',
                                                    text: 'Idcorr'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'fecha',
                                                    text: 'Fecha'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'hora',
                                                    text: 'Hora'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    minWidth: 250,
                                                    width: 250,
                                                    dataIndex: 'nombreproducto',
                                                    text: 'Nombreproducto'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'registro',
                                                    text: 'Registro',
                                                    flex: 1,
                                                    editor: {
                                                        xtype: 'numberfield'
                                                    }
                                                },
                                                {
                                                    xtype: 'actioncolumn',
                                                    maxWidth: 31,
                                                    width: 31,
                                                    align: 'right',
                                                    flex: 1,
                                                    items: [
                                                        {
                                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                                MyApp.app.getController("detalle").delRegDetalle(view, rowIndex, colIndex, item, e, record, row);
                                                            },
                                                            icon: '../../images/btns/table_delete.png'
                                                        }
                                                    ]
                                                }
                                            ],
                                            features: [
                                                {
                                                    ftype: 'grouping'
                                                }
                                            ],
                                            plugins: [
                                                {
                                                    ptype: 'rowediting',
                                                    pluginId: 'rowEditPlugIn',
                                                    listeners: {
                                                        validateedit: 'onRowEditingValidateedit',
                                                        beforeedit: 'onRowEditingBeforeEdit'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'form',
            hidden: true,
            id: 'frmDummy',
            bodyPadding: 10,
            title: 'My Form'
        }
    ],

    onRowEditingValidateedit: function(editor, context, eOpts) {

                MyApp.app.getController("detalle").updRegDetalle(editor, context,eOpts);
    },

    onRowEditingBeforeEdit: function(editor, context, eOpts) {
                var isInv =  MyApp.app.getController("main").isInvitado();
                console.log("isInv:"+isInv);

                return !isInv;
    }

});