/*
 * File: app/controller/ctrPrincipal.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.ctrPrincipal', {
    extend: 'Ext.app.Controller',

    fnCargaInicial: function() {
                this.fnRefreshClasses();
                this.fnRefreshMemory();
                this.fnRefreshStateClassesOnOff();
    },

    fnRefreshClasses: function() {
                Ext.getStore("jsonClasses").load();
    },

    fnRefreshMemory: function() {
                Ext.getStore("jsonMemory").load({
                    callback : function(records, operation, success) {
                        Ext.getCmp("formMemory").loadRecord(records[0]);
                    }
                });
    },

    fnRefreshStateClassesOnOff: function() {
                Ext.getStore("jsonGetStateClassesOnOff").load({
                    params : {
                        accion :"get"
                    },
                    callback : function(records, operation, success) {
                        console.log(records[0]);
                        console.log("to"+records[0].data.state);
                        Ext.getCmp("btnClassesOnOff").setPressed(records[0].data.state);
                    }
                });
    },

    setStateClassesOnOff: function() {
        Ext.getStore("jsonGetStateClassesOnOff").load({
            params: {
                accion : "upd",
                state :   Ext.getCmp("btnClassesOnOff").pressed
            },
            callback : function(records, operation, success) {
                console.log(records[0].data.state);
                console.log("to"+records[0].data.state);
                Ext.getCmp("btnClassesOnOff").setPressed(records[0].data.state);
            }
        });
    }

});
