/*
 * File: app/view/modal_imgUpload.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.modal_imgUpload', {
    extend: 'Ext.window.Window',
    alias: 'widget.modal_imgUpload',

    requires: [
        'MyApp.view.modal_imgUploadViewModel',
        'Ext.form.Panel',
        'Ext.form.field.File',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'modal_imgupload'
    },
    constrain: true,
    height: 512,
    id: 'modal_imgUpload',
    width: 541,
    layout: 'fit',
    title: 'Cargar imagen',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            id: 'modal_imgUpload_form',
            bodyPadding: 10,
            header: false,
            title: 'My Form',
            items: [
                {
                    xtype: 'panel',
                    height: 360,
                    id: 'panelImgContainer',
                    maxHeight: 360,
                    minHeight: 360,
                    layout: 'fit',
                    header: false,
                    title: 'My Panel'
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        padding: 5
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            maxWidth: 120,
                            minWidth: 120,
                            width: 120,
                            fieldLabel: 'Ancho',
                            labelWidth: 45,
                            name: 'base64width',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            maxWidth: 120,
                            minWidth: 120,
                            width: 120,
                            fieldLabel: 'Alto',
                            labelWidth: 45,
                            name: 'base64height',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            maxWidth: 120,
                            minWidth: 120,
                            width: 120,
                            fieldLabel: 'Kb',
                            labelWidth: 45,
                            name: 'base64weigth',
                            readOnly: true
                        }
                    ]
                },
                {
                    xtype: 'filefield',
                    anchor: '100%',
                    padding: 10,
                    fieldLabel: 'Imagen',
                    name: 'file',
                    regex: /^.*\.(png|gif|jpg|jpeg|bmp|PNG|GIF|JPG|JPEG|BMP)$/,
                    regexText: 'Solo imágenes (*.png, *.gif, *.jpg, *.peg, *.bmp)'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: 'id_cliente',
                    name: 'id_cliente'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: 'id_corr_value',
                    name: 'id_corr_value'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: 'id_param',
                    name: 'id_param'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: 'id_type',
                    name: 'id_type'
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            layout: {
                type: 'hbox',
                pack: 'end'
            },
            items: [
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var f = Ext.getCmp("modal_imgUpload_form").getForm();
                        f.submit({
                            url: "../../../EjeI?modulo=eje_generico_administradorparametros&thing=ValoresImagenUpload&accion=add",
                            waitMsg: "Cargando imagen....",
                            success: function(form, action) {
                                var resp = action.result;
                                MyApp.app.getController("ctrTool").jsonManejaError(resp, function() {
                                    Ext.getStore("values").load();
                                    Ext.getCmp("modal_imgUpload").destroy();
                                });
                            },
                            failure: function(form, action) {
                                var resp = action.result;
                                MyApp.app.getController("ctrTool").jsonManejaError(resp, function() {

                                });
                            }
                        });


                    },
                    icon: '../../images/btns/tick.ico',
                    text: 'Cargar imagen'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.getCmp("modal_imgUpload").destroy();
                    },
                    icon: '../../images/btns/cross.ico',
                    text: 'Cerrar'
                }
            ]
        }
    ],
    listeners: {
        show: 'onModal_imgUploadShow'
    },

    onModal_imgUploadShow: function(component, eOpts) {
               Ext.getCmp("modal_imgUpload_form").loadRecord(component.extraParams.record);
               var img = "data:image/png;base64,"+component.extraParams.record.get("base64file");
               Ext.getCmp("panelImgContainer").setHtml("<img src='"+img+"' style='max-height:100%; max-width:100%;'/>");

    }

});