/*
 * File: app/view/modal_modulo.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.modal_modulo', {
    extend: 'Ext.window.Window',
    alias: 'widget.modal_modulo',

    requires: [
        'MyApp.view.modal_clienteViewModel1',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.TextArea'
    ],

    viewModel: {
        type: 'modal_modulo'
    },
    constrain: true,
    height: 250,
    id: 'modal_modulo',
    width: 400,
    title: 'Módulo',
    modal: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            flex: 1,
            dock: 'bottom',
            layout: {
                type: 'hbox',
                pack: 'end'
            },
            items: [
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var f = Ext.getCmp("modal_modulo_form").getForm();
                        if (f.isValid()) {
                            f.submit({
                                url : "../../../EjeI?modulo=eje_generico_administradorparametros&thing=Modulo&accion=add",
                                waitMsg: "Esperando respuesta del servidor...",
                                success: function(form, action) {
                                    var resp = action.result;

                                    MyApp.app.getController("ctrTool").jsonManejaError(resp, function() {
                                        Ext.getStore("Modulos").load();
                                        Ext.getCmp("modal_modulo").destroy();
                                    });
                                },
                                failure: function(form, action) {
                                    var resp = action.result;
                                    MyApp.app.getController("ctrTool").jsonManejaError(resp);
                                }
                            });
                        }
                        else {
                            Ext.Msg.alert("Error","Son obligatorios todos los campos en rojo.");
                        }

                    },
                    icon: '../../images/btns/tick.ico',
                    text: 'Aceptar'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.getCmp("modal_cliente").destroy();
                    },
                    icon: '../../images/btns/cross.ico',
                    text: 'Cancelar'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            flex: 1,
            id: 'modal_modulo_form',
            bodyPadding: 10,
            header: false,
            title: 'My Form',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Nombre',
                    name: 'nombre',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Contexto',
                    name: 'contexto',
                    allowBlank: false
                },
                {
                    xtype: 'textareafield',
                    flex: 1,
                    fieldLabel: 'Descripción',
                    name: 'descripcion',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    hidden: true,
                    fieldLabel: 'Label',
                    name: 'id_modulo'
                }
            ]
        }
    ]

});