/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'Ext.form.Panel',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Separator',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Action',
        'Ext.grid.plugin.RowEditing'
    ],

    viewModel: {
        type: 'myviewport'
    },
    layout: 'fit',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            onChangeCliente: function() {
                Ext.getCmp("form_parametros").setDisabled(Ext.getCmp("combo_modulo").getValue() == null || Ext.getCmp("combo_cliente").getValue() == null );


            },
            onChangeModulo: function() {

                Ext.getCmp("form_parametros").setDisabled(Ext.getCmp("combo_modulo").getValue() == null || Ext.getCmp("combo_cliente").getValue() == null );

                /*se cargan los parametros del módulo */
                var p = Ext.getStore("params").getProxy();
                p.setExtraParam("id_modulo", Ext.getCmp("combo_modulo").getValue() );
                Ext.getStore("params").load();

                /*se bloquean los valores*/
                Ext.getCmp("panel_values").setDisabled(true);

            },
            onChangeParametro: function() {
                try {
                    var idParam = MyApp.app.getController("ctrTool").grid_getSelected("panel_keys","id_param");
                    var param   = MyApp.app.getController("ctrTool").grid_getSelected("panel_keys","nemo");
                    /*
                    console.log(sel);
                    var idParam = selected[0].data.id_param;
                    */
                    var p = Ext.getStore("values").getProxy();
                    p.setExtraParam("parametro"   , param );
                    p.setExtraParam("id_parametro", idParam );
                    p.setExtraParam("raw_modulo"      , Ext.getCmp("combo_modulo").getRawValue() );
                    p.setExtraParam("id_cliente"  , Ext.getCmp("combo_cliente").getValue() );



                    Ext.getCmp("id_parametro").setValue(idParam);
                    Ext.getStore("values").load();
                    Ext.getCmp("panel_values").setDisabled(false);
                }
                catch(e) {

                }

            },
            autoShow: true,
            height: 517,
            id: 'windowMain',
            width: 710,
            layout: 'fit',
            header: false,
            title: 'Parametros',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Servicio local',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        handler: function(item, e) {
                                            MyApp.app.getController("ctrTool").fnShowWindow("modal_confLocal");

                                        },
                                        icon: '../../images/btns/server_configuration.ico',
                                        text: 'Configurar'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                MyApp.app.getController("ctrTool").fnShowWindow("wind_checkbd");
                            },
                            icon: '../../images/btns/sql.ico',
                            text: ''
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    id: 'toolbar_clientes',
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'combo_cliente',
                            width: 500,
                            fieldLabel: 'Cliente',
                            labelWidth: 60,
                            name: 'id_cliente',
                            editable: false,
                            displayField: 'nombre_to_show',
                            store: 'Cliente',
                            valueField: 'id_cliente',
                            listeners: {
                                change: 'onCombo_clienteChange'
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {

                                MyApp.app.getController("ctrTool").fnShowWindow("modal_cliente");

                            },
                            id: 'btn_cli_add',
                            icon: '../../images/btns/user_add.ico',
                            text: ''
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                MyApp.app.getController("ctrTool").fnShowWindow("modal_cliente", null, null, function() {
                                    var record = Ext.getCmp("combo_cliente").findRecord("id_cliente", Ext.getCmp("combo_cliente").getValue());
                                    console.log(record);
                                    Ext.getCmp("modal_cliente_form").loadRecord(record);
                                });


                            },
                            disabled: true,
                            id: 'btn_cli_edit',
                            icon: '../../images/btns/edit_recipient_list.ico',
                            text: ''
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                Ext.MessageBox.confirm('Eliminar cliente', '¿Estás seguro que deseas eliminar el cliente \"'+Ext.getCmp("combo_cliente").getRawValue()+'\" ?', function(btn){
                                    console.log(btn);
                                    if(btn === 'yes'){
                                        var f = Ext.getCmp("windowMain").getForm();
                                        if (f.isValid()) {
                                            f.submit({
                                                url : "../../../EjeI?modulo=eje_generico_administradorparametros&thing=Cliente&accion=del",
                                                params: { id_cliente : Ext.getCmp("combo_cliente").getValue() },
                                                waitMsg: "Esperando al servidor...",
                                                success: function(form, action) {
                                                    var resp = action.result;

                                                    MyApp.app.getController("ctrTool").jsonManejaError(resp, function() {
                                                        Ext.getCmp("combo_cliente").clearValue();
                                                        Ext.getStore("Cliente").load();
                                                    });
                                                },
                                                failure: function(form, action) {
                                                    var resp = action.result;
                                                    MyApp.app.getController("ctrTool").jsonManejaError(resp);
                                                }
                                            });
                                        }
                                        else {
                                            Ext.Msg.alert("Error","Son obligatorios todos los campos en rojo.");
                                        }
                                    }
                                });






                            },
                            disabled: true,
                            id: 'btn_cli_del',
                            icon: '../../images/btns/user_delete.ico',
                            text: ''
                        },
                        {
                            xtype: 'tbseparator'
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    id: 'toolbar_modulos',
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'combo_modulo',
                            width: 500,
                            fieldLabel: 'M&oacute;dulo',
                            labelWidth: 60,
                            name: 'id_modulo',
                            editable: false,
                            displayField: 'nombre_to_show',
                            store: 'Modulos',
                            valueField: 'id_modulo',
                            listeners: {
                                change: 'onCombo_moduloChange'
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                MyApp.app.getController("ctrTool").fnShowWindow("modal_modulo", null, null, function() {

                                });

                            },
                            id: 'tool_btn_addmodulo',
                            icon: '../../images/btns/brick_add.ico',
                            tooltip: 'Agregar m&oacute;dulo'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {

                                MyApp.app.getController("ctrTool").fnShowWindow("modal_modulo", null, null, function() {
                                    var record = Ext.getCmp("combo_modulo").findRecord("id_modulo", Ext.getCmp("combo_modulo").getValue());
                                    console.log(record);
                                    Ext.getCmp("modal_modulo_form").loadRecord(record);
                                });



                            },
                            disabled: true,
                            id: 'tool_btn_editmodulo',
                            icon: '../../images/btns/brick_edit.ico',
                            tooltip: 'Editar'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                console.log(Ext.getCmp("combo_modulo").getValue());

                                Ext.Msg.confirm('Eliminar', '¿Estás seguro que deseas eliminar el m&oacute;dulo \"'+Ext.getCmp("combo_modulo").getRawValue()+'\"?',
                                function (id, value) {
                                    if (id === 'yes') {
                                        var form = Ext.getCmp("windowMain").getForm();

                                        form.submit({
                                            url : "../../../EjeI?modulo=eje_generico_administradorparametros&thing=Modulo&accion=del",
                                            params: { id_modulo : Ext.getCmp("combo_modulo").getValue() },
                                            waitMsg: "Esperando al servidor...",
                                            success: function(form, action) {
                                                var resp = action.result;
                                                console.log(resp);

                                                MyApp.app.getController("ctrTool").jsonManejaError(resp, function() {
                                                    Ext.getCmp("combo_modulo").clearValue();
                                                    Ext.getStore("Modulos").load();
                                                });
                                            },
                                            failure: function(form, action) {
                                                var resp = action.result;
                                                MyApp.app.getController("ctrTool").jsonManejaError(resp);
                                            }
                                        });

                                    }
                                });
                            },
                            disabled: true,
                            id: 'tool_btn_delmodulo',
                            icon: '../../images/btns/brick_delete.ico',
                            tooltip: 'eliminar'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            id: 'tool_btn_down_this',
                            icon: '../../images/btns/bullet_down.ico',
                            tooltip: 'Exportar configuraci&oacute;n del m&oacute;dulo.'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            id: 'tool_btn_down_all',
                            icon: '../../images/btns/box_down.ico',
                            tooltip: 'Exportar todas las configuraciones'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    id: 'form_parametros',
                    width: 150,
                    layout: 'border',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'west',
                            split: true,
                            id: 'panel_keys',
                            width: 300,
                            collapsible: true,
                            header: false,
                            title: '',
                            store: 'params',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'id_param',
                                    text: 'Id_corr_param'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'nemo',
                                    text: 'Par&aacute;metros',
                                    flex: 1,
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                Ext.getStore("params").load();
                                            },
                                            icon: '../../images/btns/arrow_refresh.ico',
                                            text: ''
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                Ext.Msg.prompt('Nueva KEY',
                                                'Ingrese el nombre del \"key\"',
                                                function(btn, text){
                                                    if (btn == 'ok'){
                                                        if(text == null) {
                                                            Ext.Msg.alert("Error","Key no v&aacute;lido.");
                                                        }
                                                        else if(text.length < 5) {
                                                            Ext.Msg.alert("Error","Key demasiado corto.");
                                                        }
                                                        else {
                                                            Ext.Ajax.request({
                                                                url: '../../../EjeCore',
                                                                params: {
                                                                    claseweb: "cl.eje.view.sencha.ConfSegura",
                                                                    modulo: "eje_generico_administradorparametros",
                                                                    thing: "ListaParametros",
                                                                    accion: "add",
                                                                    id_modulo: Ext.getCmp("combo_modulo").getValue(),
                                                                    key: text
                                                                },
                                                                success: function(response){
                                                                    var data = JSON.parse(response.responseText);
                                                                    console.log(data);

                                                                    if(data.success != true) {
                                                                        Ext.Msg.alert("Error","ha ocurrido un error inesperado, int&eacute;ntelo nuevamente.");

                                                                    }
                                                                    else {
                                                                        Ext.getStore("params").load();
                                                                    }

                                                                }
                                                            });
                                                        }
                                                    }
                                                });



                                            },
                                            id: 'tool_btn_add_key',
                                            icon: '../../images/btns/key_add.ico'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                console.log("idParam");

                                                var array =
                                                MyApp.app.getController("tool")
                                                .getArrayFromGrid("panel_keys","id_param");

                                                console.log(array);

                                                if( array == null ) {
                                                    Ext.Msg.alert("Error","Debes selecionar al menos un Key");
                                                }
                                                else if (array.length == 0) {
                                                    Ext.Msg.alert("Error","Debes selecionar al menos un Key");
                                                }
                                                else {
                                                    Ext.Msg.confirm('Eliminar',
                                                    '¿Estás seguro que deseas eliminar las keys seleccionadas ?',
                                                    function (id, value) {
                                                        if (id === 'yes') {
                                                            Ext.Ajax.request({
                                                                url: '../../../EjeCore',
                                                                params: {
                                                                    claseweb: "cl.eje.view.sencha.ConfSegura",
                                                                    modulo: "eje_generico_administradorparametros",
                                                                    thing: "ListaParametros",
                                                                    accion: "del",
                                                                    keys : array

                                                                },
                                                                success: function(response){
                                                                    var data = JSON.parse(response.responseText);
                                                                    console.log(data);

                                                                    if(data.success != true) {
                                                                        Ext.Msg.alert("Error","ha ocurrido un error inesperado, int&eacute;ntelo nuevamente.");

                                                                    }
                                                                    else {
                                                                        Ext.getStore("params").load();
                                                                        Ext.getCmp("panel_values").setDisabled(true);
                                                                    }

                                                                }
                                                            });
                                                        }
                                                    });
                                                }


                                            },
                                            id: 'tool_btn_del_key',
                                            icon: '../../images/btns/key_delete.ico'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true,
                                    store: 'params'
                                }
                            ],
                            selModel: {
                                selType: 'checkboxmodel',
                                mode: 'SINGLE',
                                listeners: {
                                    selectionchange: 'onCheckboxModelSelectionChange'
                                }
                            }
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            id: 'panel_values',
                            header: false,
                            title: 'My Grid Panel',
                            store: 'values',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                var params = Ext.getStore("values").getProxy().getExtraParams();


                                                Ext.Ajax.request({
                                                    url: '../../../EjeS?modulo=eje_generico_administradorparametros&thing=Valores&accion=add',
                                                    params: {
                                                        id_cliente: Ext.getCmp("combo_cliente").getValue(),
                                                        id_modulo : Ext.getCmp("combo_modulo").getValue(),
                                                        id_parametro  : Ext.getCmp("id_parametro").getValue()
                                                    },
                                                    success: function(response){
                                                        var data = JSON.parse(response.responseText);

                                                        if(data.success != true) {
                                                            Ext.Msg.alert("Error","ha ocurrido un error inesperado, int&eacute;ntelo nuevamente.");
                                                        }
                                                        else {
                                                            Ext.getStore("values").load();
                                                        }

                                                    }
                                                });



                                            },
                                            id: 'tool_btn_add_value',
                                            icon: '../../images/btns/toolbar_add.ico'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {

                                                var array =
                                                MyApp.app.getController("tool")
                                                .getArrayFromGrid("panel_values","id_corr_value");


                                                Ext.MessageBox.confirm('Eliminar', '¿Estás seguro que deseas eliminar el valor?', function(btn){
                                                    if(btn === 'yes'){
                                                        Ext.Ajax.request({
                                                            url: '../../../EjeCore',
                                                            params: {
                                                                claseweb: "cl.eje.view.sencha.ConfSegura",
                                                                modulo: "eje_generico_administradorparametros",
                                                                thing: "Valores",
                                                                accion: "del",
                                                                id_corr_value:  array
                                                            },
                                                            success: function(response){
                                                                var data = JSON.parse(response.responseText);
                                                                console.log(data);

                                                                if(data.success != true) {
                                                                    Ext.Msg.alert("Error","ha ocurrido un error inesperado, int&eacute;ntelo nuevamente.");

                                                                }
                                                                else {
                                                                    Ext.getStore("values").load();
                                                                }

                                                            }
                                                        });
                                                    }
                                                });



                                            },
                                            id: 'tool_btn_del_value',
                                            icon: '../../images/btns/toolbar_delete.ico'
                                        },
                                        {
                                            xtype: 'textfield',
                                            hidden: true,
                                            id: 'id_parametro',
                                            fieldLabel: 'Label'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true,
                                    store: 'values'
                                }
                            ],
                            columns: [
                                {
                                    xtype: 'actioncolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        this.items[0].icon = record.get("icon");
                                    },
                                    width: 25,
                                    icon: '',
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                MyApp.app.getController("ctrTool").fnShowWindow("modal_typeParam", null, record.data);

                                            },
                                            icon: ''
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'id_corr_value',
                                    text: 'Id_corr_value'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'id_corr_param',
                                    text: 'Id_corr_param'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'id_type',
                                    text: 'Id_type'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 150,
                                    dataIndex: 'data_adic1',
                                    text: 'Key',
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'valor',
                                    text: 'Valor',
                                    flex: 1,
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'data_adic2',
                                    text: 'Archivo',
                                    flex: 1
                                },
                                {
                                    xtype: 'actioncolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if(record.get("id_type") == 2) {
                                            this.items[0].icon = "../../images/btns/image.ico";
                                        }
                                        else {
                                            this.items[0].icon = "";
                                        }

                                    },
                                    width: 25,
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                window.open("../../../SLoadFile?app="+record.get("contexto_modulo")+"&param="+record.get("parametro")+"&key="+record.get("data_adic1")+"&cd=inline");

                                            },
                                            icon: '../../images/btns/image.ico'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'actioncolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {

                                        if(record.get("id_type") == 2) {
                                            this.items[0].icon = "../../images/btns/picture_save.ico";
                                        }
                                        else {
                                            this.items[0].icon = "";
                                        }

                                    },
                                    width: 25,
                                    menuDisabled: true,
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                                console.log("handler");

                                                MyApp.app.getController("ctrTool").fnShowWindow("modal_imgUpload" , null,{ record: record });

                                            },
                                            icon: '../../images/btns/picture_save.ico'
                                        }
                                    ]
                                }
                            ],
                            selModel: {
                                selType: 'checkboxmodel'
                            },
                            plugins: [
                                {
                                    ptype: 'rowediting',
                                    listeners: {
                                        validateedit: 'onRowEditingValidateedit'
                                    }
                                }
                            ]
                        }
                    ],
                    listeners: {
                        show: 'onFormShow'
                    }
                }
            ],
            listeners: {
                render: 'onWindowMainRender'
            }
        }
    ],

    onCombo_clienteChange: function(field, newValue, oldValue, eOpts) {
                Ext.getCmp("btn_cli_edit").setDisabled(newValue == null);
                Ext.getCmp("btn_cli_del").setDisabled(newValue == null);

                Ext.getCmp("windowMain").onChangeCliente();
                Ext.getCmp("windowMain").onChangeParametro();

    },

    onCombo_moduloChange: function(field, newValue, oldValue, eOpts) {
                Ext.getCmp("tool_btn_editmodulo").setDisabled(newValue == null);
                Ext.getCmp("tool_btn_delmodulo").setDisabled(newValue == null);

                Ext.getCmp("windowMain").onChangeModulo();
                //Ext.getCmp("windowMain").onChangeParametro();

    },

    onCheckboxModelSelectionChange: function(model, selected, eOpts) {
               Ext.getCmp("windowMain").onChangeParametro();
    },

    onRowEditingValidateedit: function(editor, context, eOpts) {
                var valueRecord =context.newValues;
                var value = JSON.stringify(valueRecord);

                Ext.Ajax.request({
                        url: '../../../EjeCore',
                        params: {
                            claseweb: "cl.eje.view.sencha.ConfSegura",
                            modulo: "eje_generico_administradorparametros",
                            thing: "Valores",
                            accion: "upd",
                            valueRecord: value
                        },
                        success: function(response){
                            var data = JSON.parse(response.responseText);
                            console.log(data);

                            if(data.success != true) {
                                Ext.Msg.alert("Error","ha ocurrido un error inesperado, int&eacute;ntelo nuevamente.");

                            }

                        }
                    });

    },

    onFormShow: function(component, eOpts) {
                MyApp.app.getController("tool").loadFromRepositorio();
    },

    onWindowMainRender: function(component, eOpts) {
                Ext.getCmp("windowMain").onChangeCliente();
                Ext.getCmp("windowMain").onChangeModulo();
    }

});