/*
 * File: app/view/wind_checkbd.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.wind_checkbd', {
    extend: 'Ext.window.Window',
    alias: 'widget.wind_checkbd',

    requires: [
        'MyApp.view.wind_checkbdViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Action',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'wind_checkbd'
    },
    height: 564,
    id: 'wind_checkbd',
    width: 656,
    layout: 'fit',
    title: 'CheckBD',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            header: false,
            title: 'My Grid Panel',
            store: 'store_checkbd',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'file_name',
                    text: 'File Name',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'jndi',
                    text: 'Jndi'
                },
                {
                    xtype: 'actioncolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if(record.get("estado")==1) {
                            this.items[0].icon = "../../images/btns/control_pause.ico";

                            var str = record.get("estado_desc");
                            console.log(str);
                            this.items[0].tooltip = str;

                        }
                        else if(record.get("estado")==2) {
                            this.items[0].icon = "../../images/btns/tick.ico";

                            var str = record.get("estado_desc");
                            console.log(str);
                            this.items[0].tooltip = str;
                        }
                        else if(record.get("estado")==3) {
                            this.items[0].icon = "../../images/btns/cross.ico";

                            var str = record.get("estado_desc");
                            console.log(str);
                            this.items[0].tooltip = str;
                        }
                    },
                    width: 25,
                    items: [
                        {

                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'estado_desc',
                    text: 'ToolTip'
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            layout: {
                type: 'hbox',
                pack: 'end'
            },
            items: [
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.getCmp("btn_actualizar").setDisabled(true);
                        var count = 0;

                        Ext.getStore("store_checkbd").data.each(function(record) {
                            count++;

                            try {
                                Ext.Ajax.request   ({
                                    async: false,
                                    url: '../../../EjeS',
                                    params: {
                                        modulo : "eje_generico_administradorparametros",
                                        thing  : "CheckBDexecute",
                                        accion : "get",
                                        name   : record.get("file_name")
                                    },
                                    method: 'POST',
                                    success: function(response) {

                                        var data = Ext.decode(response.responseText);
                                        console.log(record.get("file_name") + " " +data.success );

                                        if(data.success == true) {
                                            record.set("estado",2);
                                            record.set("estado_desc",data.message);
                                        }
                                        else {
                                            record.set("estado",3);
                                            record.set("estado_desc",data.message);
                                        }
                                    },
                                    failure: function(response) {
                                        record.set("estado",3);

                                    }
                                });
                            }
                            catch(e) {

                            }

                        });
                        console.log("Intentos:"+count);

                        Ext.getCmp("btn_actualizar").setDisabled(false);
                    },
                    id: 'btn_actualizar',
                    icon: '../../images/btns/tick.ico',
                    text: 'Actualizar'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.getCmp("wind_checkbd").destroy();
                    },
                    icon: '../../images/btns/cross.ico',
                    text: 'Salir'
                }
            ]
        }
    ],
    listeners: {
        render: 'onWind_checkbdRender'
    },

    onWind_checkbdRender: function(component, eOpts) {
                Ext.getStore("store_checkbd").load();
    }

});