/*
 * File: app/model/view/clas/haberes.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.view.clas.haberes', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            name: 'haber'
        },
        {
            name: 'descrip'
        },
        {
            name: 'tipo'
        },
        {
            name: 'afec_imp'
        },
        {
            name: 'imponible'
        },
        {
            name: 'id_tp'
        },
        {
            name: 'orden'
        },
        {
            name: 'wp_cod_empresa'
        },
        {
            name: 'wp_cod_planta'
        },
        {
            type: 'boolean',
            name: 'campo1'
        },
        {
            name: 'campo2'
        },
        {
            name: 'campo3'
        }
    ]
});