/*
 * File: app/view/pnl_mantenedorcargos.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.pnl_mantenedorcargos', {
    extend: 'Ext.panel.Panel',

    requires: [
        'MyApp.view.pnl_mantenedorcargosViewModel',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Hidden'
    ],

    viewModel: {
        type: 'pnl_mantenedorcargos'
    },
    constrain: true,
    autoShow: true,
    height: 350,
    id: 'pnl_Mantenedorcargos',
    width: 800,
    title: 'Mantenedor de Cargos',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'gridpanel',
            flex: 3,
            id: 'grid_Mantenedor_cargo_lista',
            title: 'Listado',
            store: 'js_Cargos',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 90,
                    dataIndex: 'cargo',
                    text: 'Codigo'
                },
                {
                    xtype: 'gridcolumn',
                    width: 350,
                    dataIndex: 'descrip',
                    text: 'Cargo'
                }
            ],
            viewConfig: {
                id: 'grid_Mantenedor_cargo_lista_view'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'txt_Mantenedor_cargo_buscar'
                        },
                        {
                            xtype: 'button',
                            id: 'btn_Mantenedor_cargo_buscar',
                            icon: '../../images/find.png'
                        },
                        {
                            xtype: 'button',
                            id: 'btn_Mantenedor_cargo_refresh',
                            margin: '0 0 0 10',
                            icon: '../../images/refresh.png',
                            text: 'Refrescar'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 4,
            autoScroll: true,
            width: 100,
            title: 'Detalle Cargo',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btn_Mantenedor_cargo_nuevo',
                            icon: '../../images/add.png',
                            text: 'Nuevo Cargo'
                        },
                        {
                            xtype: 'button',
                            id: 'btn_Mantenedor_cargo_grabar',
                            margin: '0 0 0 10',
                            icon: '../../images/save.png',
                            text: 'Grabar'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    id: 'frm_Mantenedorcargo',
                    margin: '15 5 5 5',
                    bodyPadding: 10,
                    layout: {
                        type: 'table',
                        columns: 2
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'txt_Codigo_cargo',
                            maxWidth: 200,
                            fieldLabel: 'C&oacute;digo',
                            labelWidth: 50,
                            name: 'cargo'
                        },
                        {
                            xtype: 'image',
                            height: 20,
                            id: 'img_Cargo',
                            margin: '0 0 0 -185',
                            width: 20,
                            src: '../../images/transparent.png'
                        },
                        {
                            xtype: 'textfield',
                            colspan: 2,
                            id: 'txt_Nombre_cargo',
                            maxWidth: 400,
                            width: 400,
                            fieldLabel: 'Nombre',
                            labelWidth: 50,
                            name: 'descrip'
                        },
                        {
                            xtype: 'checkboxfield',
                            colspan: 2,
                            id: 'chb_Vigente_cargo',
                            margin: '0 0 0 50',
                            name: 'vigente',
                            boxLabel: 'Cargo Vigente',
                            inputValue: 'S',
                            uncheckedValue: 'N'
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    id: 'hidden_cargo_tipo',
                    fieldLabel: 'Label'
                }
            ]
        },
        {
            xtype: 'form',
            flex: 1,
            hidden: true,
            id: 'frm_Mantenedor_cargo_existencia',
            bodyPadding: 10,
            title: 'My Form'
        }
    ]

});