/*
 * File: app/view/mainViewport.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.mainViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainViewport',

    requires: [
        'MyApp.view.mainViewportViewModel',
        'Ext.Img',
        'Ext.toolbar.Toolbar',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.tree.Column',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.grid.column.Action',
        'Ext.form.Panel'
    ],

    viewModel: {
        type: 'mainviewport'
    },
    id: 'mainViewport',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            split: true,
            height: 80,
            maxHeight: 80,
            minHeight: 80,
            collapsible: true,
            header: false,
            title: 'PeopleManager',
            items: [
                {
                    xtype: 'image',
                    src: '../../images/fondo/banner_ppm_top.png'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            id: 'main',
            layout: 'border',
            header: false,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    layout: {
                        type: 'hbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'image',
                            height: 25,
                            width: 85,
                            src: '../../images/fondo/logo_ppm.png'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'treepanel',
                    region: 'west',
                    split: true,
                    maxWidth: 350,
                    minWidth: 350,
                    width: 350,
                    collapsible: true,
                    title: 'Prestaciones',
                    store: 'jsonTree',
                    rootVisible: false,
                    viewConfig: {
                        width: 148
                    },
                    columns: [
                        {
                            xtype: 'treecolumn',
                            dataIndex: 'text',
                            text: 'Nodes',
                            flex: 1
                        },
                        {
                            xtype: 'actioncolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {

                                if(record.get("prestacion") == true || record.get("prestacionwithlogin") == true ) {
                                    console.log("setting icon ->"+record.get("text"));
                                    this.items[0].icon = "../../images/btns/clipboard_sign.ico";
                                }
                                else {
                                    this.items[0].icon = "";
                                }

                            },
                            width: 25,
                            menuDisabled: true,
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        console.log("Handler -->");

                                        if(this.icon != "") {

                                            if(record.get("prestacion") == true) {
                                                console.log("Prestacion");

                                                var url = '../../..'+record.get("relative_path");
                                                var win2 = Ext.create('Ext.window.Window', {
                                                    title: 'Copy Existing',
                                                    height: 400,
                                                    width: 500,
                                                    layout: 'fit',
                                                    constrain: true,
                                                    maximizable: true,
                                                    title: record.get("text"),
                                                    items: [{
                                                        xtype: 'box',
                                                        autoEl: {
                                                            tag: 'iframe',
                                                            src: url,
                                                        },
                                                    }]
                                                });

                                                Ext.getCmp("main_container").add(win2);
                                                win2.show();
                                            }
                                            else if(record.get("prestacionwithlogin") == true) {
                                                var url = "https://macc.corona.cl/corona/ws/per/servlet/StartSession";
                                                var win2 = Ext.create('Ext.window.Window', {
                                                    title: 'Copy Existing',
                                                    height: 400,
                                                    width: 500,
                                                    layout: 'fit',
                                                    constrain: true,
                                                    maximizable: true,
                                                    title: record.get("text"),
                                                    items: [{
                                                        xtype: 'box',
                                                        autoEl: {
                                                            tag: 'iframe',
                                                            src: url,
                                                        },
                                                    }]
                                                });

                                                Ext.getCmp("main_container").add(win2);
                                                win2.show();

                                                /*
                                                var form = Ext.getCmp("main_container").getForm();

                                                form.submit({
                                                url : url ,
                                                params : {rut : 13176947,
                                                dig  : 4,
                                                clave : 131769,
                                                htm: "https://macc.corona.cl/corona/ws/per/servlet/Tool?htm=user/usuario_frame.html"},
                                                success: function(form, action) {
                                                Ext.Msg.alert('Success', action.result.msg);
                                                },

                                                // If you don't pass success:true, it will always go here
                                                failure: function(form, action) {
                                                    try {
                                                        Ext.Msg.alert('Failed', action.result.msg);
                                                    }
                                                    catch(e) {
                                                        Ext.Msg.alert('Failed', "Error desconocido, posiblemente el sitio está abajo o no hay internet.");
                                                    }

                                                }
                                            });
                                            */
                                        }

                                    }
                                    else {
                                        console.log("Null");
                                    }
                                    }
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 310,
                                    fieldLabel: 'Buscar',
                                    labelWidth: 40
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        Ext.getStore("jsonTree").load();
                                    },
                                    icon: '../../images/btns/arrow_refresh.ico'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'form',
                    region: 'center',
                    id: 'main_container',
                    header: false,
                    title: 'My Panel'
                }
            ]
        }
    ]

});