/*
 * File: app/view/winPeriodo.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.winPeriodo', {
    extend: 'Ext.window.Window',
    alias: 'widget.winperiodo',

    requires: [
        'MyApp.view.winPeriodoViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator'
    ],

    viewModel: {
        type: 'winperiodo'
    },
    constrain: true,
    height: 309,
    id: 'winPeriodo',
    resizable: false,
    width: 649,
    layout: 'border',
    title: 'Periodo',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            region: 'west',
            split: true,
            id: 'periodoGrid',
            maxWidth: 240,
            minWidth: 240,
            width: 240,
            collapsible: true,
            header: false,
            title: 'Periodos',
            store: 'jsonPeriodo',
            viewConfig: {
                maxWidth: 240,
                minWidth: 240,
                width: 240,
                listeners: {
                    itemclick: 'onTableItemClick'
                }
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    maxWidth: 80,
                    minWidth: 80,
                    width: 80,
                    dataIndex: 'peri_id',
                    text: 'Periodo'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'peri_ano',
                    text: 'Peri Ano'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'peri_mes',
                    text: 'Peri Mes'
                },
                {
                    xtype: 'gridcolumn',
                    maxWidth: 80,
                    minWidth: 80,
                    width: 80,
                    dataIndex: 'peri_utm',
                    text: 'UTM'
                },
                {
                    xtype: 'gridcolumn',
                    maxWidth: 80,
                    minWidth: 80,
                    width: 80,
                    dataIndex: 'peri_uf',
                    text: 'UF'
                }
            ]
        },
        {
            xtype: 'form',
            region: 'center',
            id: 'periodoPanel',
            header: false,
            title: 'My Panel',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    margin: '10 20 10 20',
                    fieldLabel: 'peri_id',
                    name: 'peri_id',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    margin: '10 20 10 20',
                    fieldLabel: 'peri_ano',
                    name: 'peri_ano',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    margin: '10 20 10 20',
                    fieldLabel: 'peri_mes',
                    name: 'peri_mes',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    margin: '10 20 10 20',
                    fieldLabel: 'peri_utm',
                    name: 'peri_utm'
                },
                {
                    xtype: 'textfield',
                    margin: '10 20 10 20',
                    fieldLabel: 'peri_uf',
                    name: 'peri_uf'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    layout: {
                        type: 'hbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var form = Ext.getCmp('periodoPanel');
                                form.submit({
                                    url: '../../../servlet/EjeCore?claseweb=cl.eje.view.sencha.ConfSegura&modulo=eje_generico_cargadormaestros&thing=Periodo&accion=upd',
                                    waitMsg: 'Guardando...',
                                    method: 'POST',
                                    success: function (form, action) {
                                        var response = Ext.JSON.decode(action.response.responseText);


                                        if(response.success == true) {
                                            Ext.getStore("jsonPeriodo").load();
                                        }
                                        else {
                                            Ext.Msg.alert("Error","Ha ocurrido un error inesperado, vuelva a intentarlo");
                                        }

                                    }
                                });





                            },
                            id: 'btnGuardar',
                            icon: '../../images/btns/bullet_disk.ico',
                            text: 'Guardar'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                Ext.getCmp("winPeriodo").setItemClick(null,null);
                            },
                            id: 'btnCancelar',
                            icon: '../../images/btns/cross.png',
                            text: 'Cancelar'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var form = Ext.getCmp('periodoPanel');
                                form.submit({
                                    url: '../../../servlet/EjeCore?claseweb=cl.eje.view.sencha.ConfSegura&modulo=eje_generico_cargadormaestros&thing=Periodo&accion=del',
                                    waitMsg: 'Eliminando...',
                                    method: 'POST',
                                    success: function (form, action) {
                                        var response = Ext.JSON.decode(action.response.responseText);


                                        if(response.success == true) {
                                            Ext.getCmp("winPeriodo").setItemClick(null,null);
                                            Ext.getStore("jsonPeriodo").load();
                                        }
                                        else {
                                            Ext.Msg.alert("Error","Ha ocurrido un error inesperado, vuelva a intentarlo");
                                        }

                                    }
                                });


                            },
                            icon: '../../images/btns/delete.ico',
                            text: 'Eliminar'
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.getStore("jsonPeriodo").load();
                        this.up().up().setItemClick(null,null);

                    },
                    id: 'btnRefreshGrid',
                    icon: './../../images/btns/arrow_refresh.ico'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var form = Ext.getCmp('periodoPanel');
                        form.submit({
                            url: '../../../servlet/EjeCore?claseweb=cl.eje.view.sencha.ConfSegura&modulo=eje_generico_cargadormaestros&thing=Periodo&accion=add',
                            waitMsg: 'Agregando...',
                            method: 'POST',
                            success: function (form, action) {
                                var response = Ext.JSON.decode(action.response.responseText);


                                if(response.success == true) {
                                    Ext.getCmp("winPeriodo").setItemClick(null,null);
                                    Ext.getStore("jsonPeriodo").load();
                                }
                                else {
                                    Ext.Msg.alert("Error","Ha ocurrido un error inesperado, vuelva a intentarlo");
                                }

                            }
                        });


                    },
                    id: 'btnAddPeriodo',
                    icon: '../../images/btns/outlook_new_items.ico',
                    text: '',
                    tooltip: 'Agregar un nuevo periodo'
                }
            ]
        }
    ],
    listeners: {
        render: 'onWinPeriodoRender'
    },

    onTableItemClick: function(dataview, record, item, index, e, eOpts) {


                Ext.getCmp("winPeriodo").setItemClick(record);
    },

    onWinPeriodoRender: function(component, eOpts) {
                Ext.getStore("jsonPeriodo").load();
                this.setItemClick(null);
    },

    setItemClick: function(record) {
                if(record == null) {
                    Ext.getCmp("periodoPanel").setDisabled(true);
                }
                else {
                    Ext.getCmp("periodoPanel").setDisabled(false);

                    var form = Ext.getCmp('periodoPanel');
                    form.loadRecord(record);


                }
    }

});