/*
 * File: app/view/panelDeleted.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.panelDeleted', {
    extend: 'Ext.form.Panel',
    alias: 'widget.panelDeleted',

    requires: [
        'MyApp.view.panelSendedViewModel2',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Action',
        'Ext.toolbar.Paging',
        'Ext.selection.CheckboxModel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'paneldeleted'
    },
    height: 540,
    id: 'panelDeleted',
    width: 919,
    layout: 'border',
    bodyPadding: 10,
    title: 'Correos con problemas',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            region: 'center',
            id: 'gridPanelDeleted',
            header: false,
            title: 'My Grid Panel',
            store: 'mailStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    minWidth: 60,
                    width: 50,
                    dataIndex: 'id_correspondencia',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    maxWidth: 120,
                    minWidth: 120,
                    width: 120,
                    dataIndex: 'fec_execute',
                    text: 'Fec. a enviar'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'asunto',
                    text: 'Asunto',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'body',
                    text: 'Body'
                },
                {
                    xtype: 'actioncolumn',
                    width: 30,
                    menuDisabled: true,
                    text: 'TO',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                MyApp.app.getController("ctrTool")
                                .fnShowWindow("windowDestinatarios", null,
                                {"id_correspondencia": record.get("id_correspondencia"),
                                    "recipient":"to",
                                "id_timer": record.get("id_timer") });


                            },
                            icon: '../../images/btns/mail_yellow.ico'
                        }
                    ]
                },
                {
                    xtype: 'actioncolumn',
                    width: 30,
                    menuDisabled: true,
                    text: 'CC',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                MyApp.app.getController("ctrTool")
                                .fnShowWindow("windowDestinatarios", null,
                                {"id_correspondencia": record.get("id_correspondencia"),
                                    "recipient":"cc",
                                "id_timer": record.get("id_timer") });


                            },
                            icon: '../../images/btns/mail_yellow.ico'
                        }
                    ]
                },
                {
                    xtype: 'actioncolumn',
                    width: 30,
                    menuDisabled: true,
                    text: 'BCC',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                MyApp.app.getController("ctrTool")
                                .fnShowWindow("windowDestinatarios", null,
                                {"id_correspondencia": record.get("id_correspondencia"),
                                    "recipient":"bcc",
                                "id_timer": record.get("id_timer") });


                            },
                            icon: '../../images/btns/mail_yellow.ico'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'mailStore'
                }
            ],
            listeners: {
                itemclick: 'onGridpanelItemClick1'
            },
            selModel: {
                selType: 'checkboxmodel'
            }
        },
        {
            xtype: 'panel',
            region: 'south',
            split: true,
            height: 150,
            id: 'MensajeDeleted',
            scrollable: true,
            collapsible: true,
            title: 'Mensaje'
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.getStore("mailStore").getProxy().setExtraParam("thing", "MailProblems");
                        Ext.getStore("mailStore").load();

                    },
                    icon: '../../images/btns/arrow_refresh.ico',
                    text: ''
                }
            ]
        }
    ],
    listeners: {
        render: 'onPanelSendedRender'
    },

    onGridpanelItemClick1: function(dataview, record, item, index, e, eOpts) {

        Ext.getCmp("MensajeDeleted").update(record.get("body"));
    },

    onPanelSendedRender: function(component, eOpts) {
        Ext.getStore("mailStore").getProxy().setExtraParam("thing", "MailProblems");
        Ext.getStore("mailStore").load();

    }

});