/*
 * File: app/view/winUploadMail.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.winUploadMail', {
    extend: 'Ext.window.Window',
    alias: 'widget.winUploadMail',

    requires: [
        'MyApp.view.winUploadMailViewModel',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Label',
        'Ext.form.field.File'
    ],

    viewModel: {
        type: 'winuploadmail'
    },
    height: 190,
    id: 'winUploadMail',
    maxHeight: 190,
    minHeight: 190,
    width: 400,
    layout: 'fit',
    title: 'Cargar correos',
    modal: true,

    items: [
        {
            xtype: 'form',
            id: 'winUploadMailForm',
            bodyPadding: 10,
            header: false,
            title: 'My Form',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    layout: {
                        type: 'hbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                window.open("recurso/ejemplo.xlsx");
                            },
                            icon: '../../images/btns/mark_to_download.ico',
                            text: 'Descargar Ejemplo'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                if(Ext.getCmp("fileComponent").getValue() == "") {
                                    Ext.MessageBox.alert("Error","El archivo es inválido.");
                                }
                                else {
                                    var f = Ext.getCmp("winUploadMailForm").getForm();
                                    if(f.isValid()) {
                                        f.submit({
                                            url: "../../../EjeS?modulo=eje_generico_correspondenciaautomatica&thing=MailUploadByExcel&accion=add",
                                            waitMsg: "Los correos están siendo actualizados.<br/> Esto podría tomar varios minutos, por favor espere...",
                                            timeout : 900000,
                                            success: function(form, action) {
                                                var resp = action.result;
                                                console.log(resp);
                                                if(resp.success == true) {
                                                    Ext.Msg.alert('Correo Actualizados', resp.message, function() {
                                                        Ext.getCmp("winUploadMail");
                                                    });
                                                }
                                                else {
                                                    Ext.Msg.alert('Correo Actualizados', "Error desconocido", function() {
                                                        Ext.getCmp("winUploadMail").destroy();
                                                    });
                                                }
                                            },
                                            failure: function(form, action) {
                                                var resp = action.result;
                                                console.log(resp);

                                                Ext.Msg.alert('Correo Actualizados', "Error desconocido", function() { });
                                            }
                                        });
                                    }
                                    else {
                                        Ext.Msg.alert('Correo Actualizados', "Error desconocido", function() { });
                                    }
                                }
                            },
                            icon: '../../images/btns/tick.ico',
                            text: 'Aceptar'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                Ext.getCmp("winUploadMail").destroy();
                            },
                            icon: '../../images/btns/cross.ico',
                            text: 'Cancelar'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'label',
                    text: 'Recuerde que el archivo debe ser .XLSX y en la primera hoja solo deben venir tres columnas cuyos datos deben ser rut,nombre y correo en el mismo orden que se indica.'
                },
                {
                    xtype: 'filefield',
                    id: 'fileComponent',
                    padding: 10,
                    fieldLabel: 'Archivo',
                    name: 'fileComponent'
                }
            ]
        }
    ]

});