/*
 * File: app/model/groupCiudad_model.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.groupCiudad_model', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'nombre'
        },
        {
            type: 'boolean',
            name: 'selected'
        }
    ]
});