/*
 * File: app/model/jsonGroupModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.jsonGroupModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'id_grupo'
        },
        {
            name: 'nombre'
        },
        {
            name: 'descripcion'
        },
        {
            name: 'fec_creacion'
        },
        {
            name: 'include_personas_nuevas'
        },
        {
            name: 'include_personas_decumpleanos'
        },
        {
            name: 'include_personas_genero'
        },
        {
            name: 'include_personas_cc'
        },
        {
            name: 'include_personas_selected'
        },
        {
            name: 'path_class'
        },
        {
            name: 'vigente'
        },
        {
            name: 'include_personas_empresa'
        },
        {
            name: 'include_personas_cargo'
        },
        {
            name: 'include_personas_ciudad'
        },
        {
            name: 'include_personas_comuna'
        },
        {
            name: 'include_personas_organica'
        }
    ]
});