/*
 * File: app/view/grid_Colaborador.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.grid_Colaborador', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.grid_Colaborador',

    requires: [
        'MyApp.view.grid_ColaboradorViewModel',
        'Ext.grid.column.Action',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'grid_colaborador'
    },
    autoScroll: true,
    height: 400,
    id: 'grid_Colaborador',
    width: 800,
    title: 'Lista Colaboradores',
    forceFit: true,
    store: 'js_Colaborador',

    columns: [
        {
            xtype: 'gridcolumn',
            width: 90,
            align: 'right',
            dataIndex: 'rutdv',
            text: 'Rut'
        },
        {
            xtype: 'gridcolumn',
            width: 250,
            dataIndex: 'nombre',
            text: 'Nombre'
        },
        {
            xtype: 'gridcolumn',
            width: 250,
            dataIndex: 'cargo',
            text: 'Cargo'
        },
        {
            xtype: 'gridcolumn',
            width: 180,
            align: 'center',
            dataIndex: 'ult_cambio',
            text: 'Ultima Actualización Clave'
        },
        {
            xtype: 'actioncolumn',
            width: 60,
            align: 'center',
            dataIndex: 'rut',
            items: [
                {
                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                        var nombre = "Colaborador : " + record.get("nombre");
                        var rutdv = "Rut : " + record.get("rutdv");
                        var clave = "miclavees?";
                        var win = Ext.create('widget.window', {
                            title: 'Visualización Clave Colaborador',
                            header: { titlePosition: 2, titleAlign: 'center'},
                            closable: true,
                            closeAction: 'hide',
                            maximizable: false,
                            width: 400,
                            minWidth: 150,
                            height: 250,
                            modal: true,
                            layout: { type: 'border',padding: 5 },
                            items: [
                            {
                                region: 'center',
                                xtype: 'panel',
                                layout: { type: 'vbox', align: 'center' },
                                items: [
                                {
                                    xtype: 'label',
                                    margin: '30 10 2 10',
                                    text: nombre
                                },
                                {
                                    xtype: 'label',
                                    margin: '2 10 10 10',
                                    text: rutdv
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '20 10 20 10',
                                    fieldLabel: 'Clave',
                                    labelAlign: 'right',
                                    labelWidth: 50,
                                    inputType: 'password',
                                    value: clave,
                                    id: 'txt_clave_ver'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    margin: '10 10 10 10',
                                    boxLabel: 'Ver Clave',
                                    id: 'chb_clave_ver',
                                    handler: function(checkbox, checked) {
                                        if (checked) {
                                            Ext.getCmp('txt_clave_ver').inputEl.dom.type = 'text';
                                        }
                                        else {
                                            Ext.getCmp('txt_clave_ver').inputEl.dom.type = 'password';
                                        }
                                    }
                                }
                                ]
                            },
                            {
                                region: 'south',
                                xtype: 'toolbar',
                                items: [
                                {
                                    xtype: 'button',
                                    id: 'btn_Cerrar_ver',
                                    icon: '../../images/exit.png',
                                    text: 'Cerrar'
                                }
                                ]
                            }
                            ]
                        });
                        win.show(this, function() {});
                    },
                    icon: '../../images/viewkey.png',
                    tooltip: 'Ver Clave Colaborador'
                }
            ]
        },
        {
            xtype: 'actioncolumn',
            width: 60,
            layout: 'fit',
            align: 'center',
            dataIndex: 'rut',
            items: [
                {
                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                        var nombre = "Colaborador : " + record.get("nombre");
                        var rutdv = "Rut : " + record.get("rutdv");
                        var clave = "miclavees?";
                        var win = Ext.create('widget.window', {
                            title: 'Cambio Clave Colaborador',
                            header: { titlePosition: 2, titleAlign: 'center'},
                            closable: true,
                            closeAction: 'hide',
                            maximizable: false,
                            width: 400,
                            minWidth: 150,
                            height: 250,
                            modal: true,
                            layout: { type: 'border',padding: 5 },
                            items: [
                            { region: 'center',
                                xtype: 'panel',
                                layout: { type: 'vbox', align: 'center' },
                                items: [
                                {
                                    xtype: 'label',
                                    margin: '10 10 2 10',
                                    text: nombre
                                },
                                {
                                    xtype: 'label',
                                    margin: '2 10 10 10',
                                    text: rutdv
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 10 2 10',
                                    fieldLabel: 'Clave',
                                    labelAlign: 'right',
                                    labelWidth: 150,
                                    inputType: 'password',
                                    value: clave,
                                    id: 'txt_clave_cambiar'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '2 10 2 10',
                                    fieldLabel: 'Nueva Clave',
                                    labelAlign: 'right',
                                    labelWidth: 150,
                                    inputType: 'password',
                                    id: 'txt_nuevaclave_cambiar'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '2 10 2 10',
                                    fieldLabel: 'Confirmar Nueva Clave',
                                    labelAlign: 'right',
                                    labelWidth: 150,
                                    inputType: 'password',
                                    id: 'txt_confirmarclave_cambiar'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    margin: '10 10 10 10',
                                    boxLabel: 'Ver Clave',
                                    id: 'chb_clave_cambiar',
                                    handler: function(checkbox, checked) {
                                        if (checked) {
                                            Ext.getCmp('txt_clave_cambiar').inputEl.dom.type = 'text';
                                            Ext.getCmp('txt_nuevaclave_cambiar').inputEl.dom.type = 'text';
                                            Ext.getCmp('txt_confirmarclave_cambiar').inputEl.dom.type = 'text';
                                        }
                                        else {
                                            Ext.getCmp('txt_clave_cambiar').inputEl.dom.type = 'password';
                                            Ext.getCmp('txt_nuevaclave_cambiar').inputEl.dom.type = 'password';
                                            Ext.getCmp('txt_confirmarclave_cambiar').inputEl.dom.type = 'password';
                                        }
                                    }
                                }
                                ]
                            },
                            {
                                region: 'south',
                                xtype: 'toolbar',
                                items: [
                                {
                                    xtype: 'button',
                                    id: 'btn_Grabar_cambiar',
                                    icon: '../../images/save.png',
                                    text: 'Grabar'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_Cerrar_cambiar',
                                    icon: '../../images/exit.png',
                                    text: 'Cerrar'
                                }
                                ]
                            }
                            ]
                        });
                        win.show(this, function() {});
                    },
                    icon: '../../images/changekey.png',
                    tooltip: 'Cambiar Clave'
                }
            ]
        },
        {
            xtype: 'actioncolumn',
            width: 60,
            align: 'center',
            dataIndex: 'rut',
            icon: '../../images/sendkey.png',
            items: [
                {
                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                        var nombre = "Colaborador : " + record.get("nombre");
                        var rutdv = "Rut : " + record.get("rutdv");
                        var clave = "miclavees?";
                        var win = Ext.create('widget.window', {
                            title: 'Envío Clave a Colaborador',
                            header: { titlePosition: 2, titleAlign: 'center'},
                            closable: true,
                            closeAction: 'hide',
                            maximizable: false,
                            width: 400,
                            minWidth: 150,
                            height: 250,
                            modal: true,
                            layout: { type: 'border',padding: 5 },
                            items: [
                            { region: 'center',
                                xtype: 'panel',
                                layout: { type: 'vbox', align: 'center' },
                                items: [
                                {
                                    xtype: 'label',
                                    margin: '10 10 2 10',
                                    text: nombre
                                },
                                {
                                    xtype: 'label',
                                    margin: '2 10 10 10',
                                    text: rutdv
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 10 2 10',
                                    fieldLabel: 'Clave',
                                    labelAlign: 'right',
                                    labelWidth: 150,
                                    inputType: 'password',
                                    value: clave,
                                    id: 'txt_clave_enviar'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '2 10 2 10',
                                    fieldLabel: 'Correo Colaborador',
                                    labelAlign: 'right',
                                    labelWidth: 150,
                                    inputType: 'text',
                                    id: 'txt_correo_enviar'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    margin: '10 10 10 10',
                                    boxLabel: 'Ver Clave',
                                    id: 'chb_clave_enviar',
                                    handler: function(checkbox, checked) {
                                        if (checked) {
                                            Ext.getCmp('txt_clave_enviar').inputEl.dom.type = 'text';
                                        }
                                        else {
                                            Ext.getCmp('txt_clave_enviar').inputEl.dom.type = 'password';
                                        }
                                    }
                                }
                                ]
                            },
                            {
                                region: 'south',
                                xtype: 'toolbar',
                                items: [
                                {
                                    xtype: 'button',
                                    id: 'btn_Enviar_enviar',
                                    icon: '../../images/sendpass.png',
                                    text: 'Enviar Clave'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_Cerrar_cambiar',
                                    icon: '../../images/exit.png',
                                    text: 'Cerrar'
                                }
                                ]
                            }
                            ]
                        });
                        win.show(this, function() {});
                    },
                    icon: '../../images/sendkey.png',
                    tooltip: 'Enviar Clave Colaborador'
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'textfield',
                    id: 'txt_Filtro'
                },
                {
                    xtype: 'button',
                    id: 'btn_Filtro',
                    icon: '../../images/find.png'
                },
                {
                    xtype: 'button',
                    id: 'btn_Refresh',
                    icon: '../../images/refresh.png'
                },
                {
                    xtype: 'button',
                    hidden: true,
                    id: 'btn_Exportar',
                    margin: '0 0 0 45',
                    icon: '../../images/excel.png',
                    text: 'Exportar'
                }
            ]
        }
    ]

});