/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'MyApp.view.MyViewportViewModel',
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.form.field.Text',
        'Ext.grid.column.Action',
        'Ext.view.Table',
        'Ext.button.Button',
        'Ext.toolbar.Paging',
        'Ext.selection.CheckboxModel',
        'Ext.grid.plugin.CellEditing'
    ],

    viewModel: {
        type: 'myviewport'
    },
    layout: 'fit',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            id: 'form_sendMail',
            width: 100,
            layout: 'fit',
            header: false,
            title: 'My Form',
            items: [
                {
                    xtype: 'gridpanel',
                    height: 400,
                    id: 'grid_Colaborador',
                    scrollable: true,
                    width: 800,
                    title: 'Lista Colaboradores',
                    forceFit: true,
                    store: 'js_Colaborador',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'mail',
                            text: 'Mail',
                            editor: {
                                xtype: 'textfield',
                                readOnly: false,
                                editable: false,
                                selectOnFocus: true
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 90,
                            align: 'right',
                            dataIndex: 'rutdv',
                            text: 'Rut',
                            editor: {
                                xtype: 'textfield',
                                editable: false,
                                selectOnFocus: true
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 250,
                            dataIndex: 'nombre',
                            text: 'Nombre',
                            editor: {
                                xtype: 'textfield',
                                readOnly: false,
                                editable: false,
                                selectOnFocus: true
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 250,
                            dataIndex: 'cargo',
                            text: 'Cargo',
                            editor: {
                                xtype: 'textfield',
                                readOnly: false,
                                editable: false,
                                selectOnFocus: true
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 180,
                            align: 'center',
                            dataIndex: 'ult_cambio',
                            text: 'Ultima Actualización Clave',
                            editor: {
                                xtype: 'textfield',
                                readOnly: false,
                                editable: false,
                                selectOnFocus: true
                            }
                        },
                        {
                            xtype: 'actioncolumn',
                            width: 60,
                            align: 'center',
                            dataIndex: 'rut',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var nombre = "Colaborador : " + record.get("nombre");
                                        var rutdv = "Rut : " + record.get("rutdv");

                                        var rut = record.get("rut");
                                        var clave = "";
                                        var store = Ext.getStore("js_Clave");
                                        store.load({
                                            params:{'rut': rut},
                                            scope: this,
                                            callback: function(records, operation, success) {
                                                if (success) {
                                                    if(records[0] !== undefined) {
                                                        clave = records[0].data.valor;
                                                        var win = Ext.create('widget.window', {
                                                            title: 'Visualización Clave Colaborador',
                                                            header: { titlePosition: 2, titleAlign: 'center'},
                                                            closable: true,
                                                            closeAction: 'hide',
                                                            maximizable: false,
                                                            width: 400,
                                                            minWidth: 150,
                                                            height: 250,
                                                            modal: true,
                                                            layout: { type: 'border',padding: 5 },
                                                            items: [
                                                            {
                                                                region: 'center',
                                                                xtype: 'panel',
                                                                layout: { type: 'vbox', align: 'center' },
                                                                items: [
                                                                {
                                                                    xtype: 'label',
                                                                    margin: '30 10 2 10',
                                                                    text: nombre
                                                                },
                                                                {
                                                                    xtype: 'label',
                                                                    margin: '2 10 10 10',
                                                                    text: rutdv
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    margin: '20 10 20 10',
                                                                    fieldLabel: 'Clave',
                                                                    labelAlign: 'right',
                                                                    labelWidth: 50,
                                                                    inputType: 'password',
                                                                    value: clave,
                                                                    id: 'txt_clave_ver'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    margin: '10 10 10 10',
                                                                    boxLabel: 'Ver Clave',
                                                                    id: 'chb_clave_ver',
                                                                    handler: function(checkbox, checked) {
                                                                        if (checked) {
                                                                            Ext.getCmp('txt_clave_ver').inputEl.dom.type = 'text';
                                                                        }
                                                                        else {
                                                                            Ext.getCmp('txt_clave_ver').inputEl.dom.type = 'password';
                                                                        }
                                                                    }
                                                                }
                                                                ]
                                                            },
                                                            {
                                                                region: 'south',
                                                                xtype: 'toolbar',
                                                                items: [
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'btn_Cerrar_ver',
                                                                    icon: '../../images/exit.png',
                                                                    text: 'Cerrar',
                                                                    handler: function(button,click) {
                                                                        win.close();
                                                                    }
                                                                }
                                                                ]
                                                            }
                                                            ]
                                                        });
                                                        win.show(this, function() {});
                                                    }
                                                }
                                            }
                                        });
                                    },
                                    icon: '../../images/viewkey.png',
                                    tooltip: 'Ver Clave Colaborador'
                                }
                            ]
                        },
                        {
                            xtype: 'actioncolumn',
                            width: 60,
                            layout: 'fit',
                            align: 'center',
                            dataIndex: 'rut',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var nombre = "Colaborador : " + record.get("nombre");
                                        var rutdv = "Rut : " + record.get("rutdv");

                                        var rut = record.get("rut");
                                        var clave = "";
                                        var store = Ext.getStore("js_Clave");
                                        store.load({
                                            params:{'rut': rut},
                                            scope: this,
                                            callback: function(records, operation, success) {
                                                if (success) {
                                                    if(records[0] !== undefined) {
                                                        clave = records[0].data.valor;
                                                        var win = Ext.create('widget.window', {
                                                            title: 'Cambio Clave Colaborador',
                                                            header: { titlePosition: 2, titleAlign: 'center'},
                                                            closable: true,
                                                            closeAction: 'hide',
                                                            maximizable: false,
                                                            width: 400,
                                                            minWidth: 150,
                                                            height: 250,
                                                            modal: true,
                                                            layout: { type: 'border',padding: 5 },
                                                            items: [
                                                            { region: 'center',
                                                                xtype: 'panel',
                                                                layout: { type: 'vbox', align: 'center' },
                                                                items: [
                                                                {
                                                                    xtype: 'label',
                                                                    margin: '10 10 2 10',
                                                                    text: nombre
                                                                },
                                                                {
                                                                    xtype: 'label',
                                                                    margin: '2 10 10 10',
                                                                    text: rutdv
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    margin: '10 10 2 10',
                                                                    fieldLabel: 'Clave',
                                                                    labelAlign: 'right',
                                                                    labelWidth: 150,
                                                                    inputType: 'password',
                                                                    value: clave,
                                                                    id: 'txt_clave_cambiar'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    margin: '2 10 2 10',
                                                                    fieldLabel: 'Nueva Clave',
                                                                    labelAlign: 'right',
                                                                    labelWidth: 150,
                                                                    inputType: 'password',
                                                                    id: 'txt_nuevaclave_cambiar'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    margin: '2 10 2 10',
                                                                    fieldLabel: 'Confirmar Nueva Clave',
                                                                    labelAlign: 'right',
                                                                    labelWidth: 150,
                                                                    inputType: 'password',
                                                                    id: 'txt_confirmarclave_cambiar'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    margin: '10 10 10 10',
                                                                    boxLabel: 'Ver Clave',
                                                                    id: 'chb_clave_cambiar',
                                                                    handler: function(checkbox, checked) {
                                                                        if (checked) {
                                                                            Ext.getCmp('txt_clave_cambiar').inputEl.dom.type = 'text';
                                                                            Ext.getCmp('txt_nuevaclave_cambiar').inputEl.dom.type = 'text';
                                                                            Ext.getCmp('txt_confirmarclave_cambiar').inputEl.dom.type = 'text';
                                                                        }
                                                                        else {
                                                                            Ext.getCmp('txt_clave_cambiar').inputEl.dom.type = 'password';
                                                                            Ext.getCmp('txt_nuevaclave_cambiar').inputEl.dom.type = 'password';
                                                                            Ext.getCmp('txt_confirmarclave_cambiar').inputEl.dom.type = 'password';
                                                                        }
                                                                    }
                                                                }
                                                                ]
                                                            },
                                                            {
                                                                region: 'south',
                                                                xtype: 'toolbar',
                                                                items: [
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'btn_Grabar_cambiar',
                                                                    icon: '../../images/save.png',
                                                                    text: 'Grabar',
                                                                    handler: function(button,click) {
                                                                        var clave0 = Ext.getCmp("txt_clave_cambiar").getValue();
                                                                        var clave1 = Ext.getCmp("txt_nuevaclave_cambiar").getValue();
                                                                        var clave2 = Ext.getCmp("txt_confirmarclave_cambiar").getValue();
                                                                        if(clave1===clave2) {
                                                                            var storeSave = Ext.getStore("js_Grabaclave");
                                                                            storeSave.load({
                                                                                params:{'rut': rut,'clave':clave0,'nuevaclave':clave1},
                                                                                scope: this,
                                                                                callback: function(records, operation, success) {
                                                                                    if (success) {
                                                                                        win.close();
                                                                                        Ext.MessageBox.alert('Estado', 'Clave actualizada con éxito...');
                                                                                    }
                                                                                }
                                                                            });
                                                                        }
                                                                        else {
                                                                            Ext.MessageBox.alert('Estado', 'Las claves deben coincidir para poder actualizar...');
                                                                        }
                                                                    }
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'btn_Cerrar_cambiar',
                                                                    icon: '../../images/exit.png',
                                                                    text: 'Cerrar',
                                                                    handler: function(button,click) {
                                                                        win.close();
                                                                    }
                                                                }
                                                                ]
                                                            }
                                                            ]
                                                        });
                                                        win.show(this, function() {});
                                                    }
                                                }
                                            }
                                        });





                                    },
                                    icon: '../../images/changekey.png',
                                    tooltip: 'Cambiar Clave'
                                }
                            ]
                        },
                        {
                            xtype: 'actioncolumn',
                            disabled: false,
                            width: 60,
                            align: 'center',
                            dataIndex: 'rut',
                            icon: '../../images/sendkey.png',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var rut = record.get("rut");
                                        var rutdv = "Rut : " + record.get("rutdv");
                                        var nombre2 = record.get("nombre");
                                        var nombre = "Colaborador : " + record.get("nombre");
                                        var clave = "";
                                        var mail = "";
                                        var store = Ext.getStore("js_Clave");

                                        console.log(store);

                                        store.load({
                                            params:{'rut': rut},
                                            scope: this,
                                            callback: function(records, operation, success) {
                                                if (success) {
                                                    if(records[0] !== undefined) {
                                                        clave = records[0].data.valor;
                                                        mail = records[0].data.mail;

                                                        var win = Ext.create('widget.window', {
                                                            id: "windowSendMail",
                                                            title: 'Envío Clave a Colaborador',
                                                            header: { titlePosition: 2, titleAlign: 'center'},
                                                            closable: true,
                                                            closeAction: 'hide',
                                                            maximizable: false,
                                                            width: 400,
                                                            minWidth: 150,
                                                            height: 250,
                                                            modal: true,
                                                            layout: { type: 'border',padding: 5 },
                                                            items: [
                                                            { region: 'center',
                                                                xtype: 'panel',
                                                                layout: { type: 'vbox', align: 'center' },
                                                                items: [
                                                                {
                                                                    xtype: 'label',
                                                                    margin: '10 10 2 10',
                                                                    text: nombre
                                                                },
                                                                {
                                                                    xtype: 'label',
                                                                    margin: '2 10 10 10',
                                                                    text: rutdv
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    margin: '10 10 2 10',
                                                                    fieldLabel: 'Clave',
                                                                    labelAlign: 'right',
                                                                    labelWidth: 150,
                                                                    inputType: 'password',
                                                                    value: clave,
                                                                    id: 'txt_clave_enviar',
                                                                    readOnly:true
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    margin: '2 10 2 10',
                                                                    fieldLabel: 'Correo Colaborador',
                                                                    labelAlign: 'right',
                                                                    labelWidth: 150,
                                                                    inputType: 'text',
                                                                    value: mail,
                                                                    id: 'txt_correo_enviar'
                                                                },
                                                                {
                                                                    xtype: 'checkboxfield',
                                                                    margin: '10 10 10 10',
                                                                    boxLabel: 'Ver Clave',
                                                                    id: 'chb_clave_enviar',
                                                                    handler: function(checkbox, checked) {
                                                                        if (checked) {
                                                                            Ext.getCmp('txt_clave_enviar').inputEl.dom.type = 'text';
                                                                        }
                                                                        else {
                                                                            Ext.getCmp('txt_clave_enviar').inputEl.dom.type = 'password';
                                                                        }
                                                                    }
                                                                }
                                                                ]
                                                            },
                                                            {
                                                                region: 'south',
                                                                xtype: 'toolbar',
                                                                items: [
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'btn_Enviar_enviar',
                                                                    icon: '../../images/sendpass.png',
                                                                    text: 'Enviar Clave',
                                                                    waitMsg: "Enviando correo...",
                                                                    handler: function(button,click) {

                                                                        var correo = Ext.getCmp("txt_correo_enviar").getValue();
                                                                        console.log(correo);

                                                                        if(correo != null) {
                                                                            if(correo.trim().length != 0) {

                                                                                var storeSend = Ext.getStore("js_Sendclave");
                                                                                storeSend.load({
                                                                                    params:{'nombre': nombre2,'clave':clave,'mail':Ext.getCmp('txt_correo_enviar').getValue(), "rut": rut},
                                                                                    scope: this,
                                                                                    callback: function(records, operation, success) {
                                                                                        if (success) {
                                                                                            win.close();
                                                                                            Ext.MessageBox.alert('Estado', 'La Clave fue enviada con éxito... !!!');
                                                                                        }
                                                                                        else {
                                                                                            Ext.MessageBox.alert('Estado', 'La Clave no pudo ser enviada... !!!');
                                                                                        }
                                                                                    }
                                                                                });
                                                                            }
                                                                            else {
                                                                                Ext.MessageBox.alert('Error', 'Correo inválido. Debe ingresar uno válido');
                                                                            }
                                                                        }
                                                                        else {
                                                                            Ext.MessageBox.alert('Error', 'Correo inválido. Debe ingresar uno válido');
                                                                        }
                                                                    }
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    id: 'btn_Cerrar_cambiar',
                                                                    icon: '../../images/exit.png',
                                                                    text: 'Cerrar',
                                                                    handler: function(button,click) {
                                                                        win.close();
                                                                    }
                                                                }
                                                                ]
                                                            }
                                                            ]
                                                        });

                                                        win.show(this, function() {});

                                                    }}} });
                                    },
                                    icon: '../../images/sendkey.png',
                                    tooltip: 'Enviar Clave Colaborador'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'txt_Filtro',
                                    listeners: {
                                        specialkey: 'onTxt_FiltroSpecialkey'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    id: 'btn_Filtro',
                                    icon: '../../images/find.png'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    id: 'btn_Refresh',
                                    icon: '../../images/refresh.png'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    id: 'btn_Exportar',
                                    margin: '0 0 0 45',
                                    icon: '../../images/excel.png',
                                    text: 'Exportar'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        Ext.MessageBox.confirm('Recordar claves', 'Estás a un clic de enviarle la clave a todas las personas seleccionadas.<br/>¿Estás seguro de querer hacerlo?', function(btn){
                                            console.log(btn);
                                            if(btn === 'yes'){
                                                var s = MyApp.app.getController("ctrTool").grid_getSelected("grid_Colaborador","rut");

                                                var f = Ext.getCmp("form_sendMail").getForm();
                                                f.submit({
                                                    url : "../../../EjeS?modulo=eje_generico_administradorclaves&thing=SendCorreosMasivos&accion=add",
                                                    params : {
                                                        ruts :  s
                                                    },
                                                    success: function(form, action) {
                                                        var resp = action.result;

                                                        if(resp.success == true) {
                                                            Ext.Msg.alert("Envío de claves", resp.message);
                                                        }
                                                        else {
                                                            Ext.Msg.alert('Envío de claves', resp.message);
                                                        }

                                                    },
                                                    failure: function(form, action) {
                                                        var resp = action.result;

                                                        if(resp.success == true) {
                                                            Ext.Msg.alert("Envío de claves", resp.message);
                                                        }
                                                        else {
                                                            Ext.Msg.alert('Envío de claves', resp.message);
                                                        }
                                                    }
                                                });
                                            }
                                        });


                                    },
                                    disabled: true,
                                    id: 'btn_sendclave',
                                    icon: '../../images/sendkey.png'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'js_Colaborador'
                        }
                    ],
                    selModel: {
                        selType: 'checkboxmodel',
                        listeners: {
                            selectionchange: 'onCheckboxModelSelectionChange'
                        }
                    },
                    plugins: [
                        {
                            ptype: 'cellediting'
                        }
                    ]
                }
            ]
        }
    ],

    onTxt_FiltroSpecialkey: function(field, e, eOpts) {
        if(e.keyCode == 13) {
            var filtro = Ext.getCmp("txt_Filtro").getValue();
            Ext.getStore("js_Colaborador").load( { params: { "filtro" : filtro} } );

        }


    },

    onCheckboxModelSelectionChange: function(model, selected, eOpts) {
               Ext.getCmp("btn_sendclave").setDisabled(!(selected.length > 0) );

    }

});